vZome/vzome

desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java
Manually merged from @david-hall PR on the old desktop repo
=> Log encoding

core/src/main/java/com/vzome/core/algebra/AlgebraicField.java, core/src/test/java/com/vzome/core/algebra/AlgebraicFieldTest.java
David found this defect; reciprocal of 0 for most fields was 1.
=> Implement divide-by-zero test for AlgebraicField.reciprocal()

core/src/main/java/com/vzome/core/editor/Application.java
* Restore use of keySet() in getFieldNames()
=> Use Supplier interface to implement lazy loading of FieldApplications.

.travis.yml, build.gradle, desktop/build.gradle, desktop/platform/mac/build.gradle, desktop/platform/windows/build.gradle, settings.gradle
Gradle fixes to restore ability to build Mac and Windows distributions.
=> Desktop builds

desktop/build.gradle, desktop/src/main/resources/org/vorthmann/zome/app/defaultPrefs.properties
Setting correct startScripts.applicationName.
Also, made the built-in default properties support the full vZome editor.
=> Adding correct archiveNamefor Linux distZip

core/src/main/java/com/vzome/core/editor/DocumentModel.java, desktop/src/main/java/com/vzome/desktop/controller/CameraController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/ApplicationController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/PickingController.java, desktop/src/main/java/org/vorthmann/zome/ui/ModelPanel.java
Made a few enhancements to the context menu.
1) "Look at this" now works on the midpoint of struts and panels, not just on connectors.
2) "Show properties" is always enabled and shows the field name if no part is chosen.
3) Optionally, camera info is shown too if enabled in the preferences file.
=> Context Menu Enhancements

core/src/main/java/com/vzome/core/algebra/AlgebraicVectors.java, core/src/main/java/com/vzome/core/construction/LinePlaneIntersectionPoint.java, core/src/main/java/com/vzome/core/parts/FastDefaultStrutGeometry.java
Also, moved line-plane intersection to AlgebraicVectors class.
=> Much improved auto strut shapes

core/src/main/java/com/vzome/core/editor/ChangeManifestations.java, core/src/main/java/com/vzome/core/editor/DocumentModel.java, core/src/main/java/com/vzome/core/editor/EditorModel.java, core/src/main/java/com/vzome/core/editor/Manifestations.java, core/src/main/java/com/vzome/core/editor/ShowNormals.java, core/src/main/java/com/vzome/core/editor/Validate2Manifold.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
Added ShowNormals and Validate2Manifold commands.
=> Support for 3d printing

core/src/main/java/com/vzome/core/construction/ChangeOfBasis.java, core/src/main/java/com/vzome/core/math/symmetry/AbstractSymmetry.java
Commented out two places where matrices were being printed as json.
=> Remove diagnostic calls to println() from two places.

core/src/regression/files/2018/07-Jul/18-David-JoinSkewLines/joinSkewLines.vZome, core/src/regression/files/sniff-test.vZome-files
Enable existing regression test files for color mapping commands
=> Add regression test file for JoinSkewLines command

core/src/main/java/com/vzome/core/editor/Application.java, core/src/main/java/com/vzome/core/exporters/ObservableJsonExporter.java, core/src/main/java/com/vzome/core/exporters/VsonExporter.java
This exporter produces a very simple JSON format as required currently
by https://beta.observablehq.com/@vorth/vzome-rendering-component.
I also reformatted VsonExporter.java.
=> Added ObservableJsonExporter

core/src/main/java/com/vzome/core/editor/PlaneSelectionTool.java, core/src/main/java/com/vzome/core/kinds/GoldenFieldApplication.java
Also reformatted GoldenFieldApplication.
=> Fixed PlaneSelectionTool.Factory

core/src/main/java/com/vzome/core/algebra/AlgebraicNumber.java, core/src/main/java/com/vzome/core/algebra/AlgebraicVector.java, core/src/main/java/com/vzome/core/algebra/BigRational.java, core/src/main/java/com/vzome/core/construction/Polygon.java, core/src/main/java/com/vzome/core/editor/DocumentModel.java, core/src/main/java/com/vzome/core/editor/SymmetrySystem.java, core/src/main/java/com/vzome/core/exporters/ObservableJsonExporter.java, core/src/main/java/com/vzome/core/exporters/VefExporter.java, core/src/main/java/com/vzome/core/exporters/VsonExporter.java, core/src/main/java/com/vzome/core/math/Polyhedron.java, core/src/main/java/com/vzome/core/math/RealVector.java, core/src/main/java/com/vzome/core/math/symmetry/AbstractSymmetry.java, core/src/main/java/com/vzome/core/math/symmetry/Direction.java, core/src/main/java/com/vzome/core/render/Shapes.java, core/src/main/java/com/vzome/core/viewing/AbstractShapes.java, core/src/main/java/com/vzome/core/viewing/ExportedVEFShapes.java, core/src/main/java/com/vzome/core/viewing/ExportedVEFStrutGeometry.java, core/src/test/java/com/vzome/core/apps/DumpShapeJson.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, server/src/main/java/com/vzome/server/RemoteClientRendering.java
Also refinements to the shape naming, for predictability.
Lots of formatting cleanups, removing tabs.
Lots of work on JSON export of shapes, symmetry.
=> JSON exports via copy for Observable

core/src/main/java/com/vzome/api/Vector.java, core/src/main/java/com/vzome/core/algebra/AlgebraicVectors.java, core/src/main/java/com/vzome/core/commands/CommandPolygon.java, core/src/main/java/com/vzome/core/construction/PerpendicularLine.java, core/src/main/java/com/vzome/core/construction/PlaneExtensionOfPolygon.java, core/src/main/java/com/vzome/core/construction/Polygon.java, core/src/main/java/com/vzome/core/construction/PolygonFromVertices.java, core/src/main/java/com/vzome/core/construction/PolygonRotated4D.java, core/src/main/java/com/vzome/core/construction/PolygonVertex.java, core/src/main/java/com/vzome/core/construction/Segment.java, core/src/main/java/com/vzome/core/construction/SegmentCrossProduct.java, core/src/main/java/com/vzome/core/construction/TransformedPolygon.java, core/src/main/java/com/vzome/core/editor/DocumentModel.java, core/src/main/java/com/vzome/core/editor/ShowNormals.java, core/src/main/java/com/vzome/core/editor/ShowVertices.java, core/src/main/java/com/vzome/core/editor/Symmetry4d.java, core/src/main/java/com/vzome/core/math/Polyhedron.java, core/src/main/java/com/vzome/core/math/symmetry/AbstractSymmetry.java, core/src/main/java/com/vzome/core/math/symmetry/Direction.java, core/src/main/java/com/vzome/core/model/RealizedModel.java, core/src/main/java/com/vzome/core/parts/DefaultStrutGeometry.java, core/src/main/java/com/vzome/core/parts/FastDefaultStrutGeometry.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/StrutBuilderController.java
Refactoring normal calculations, partly to use common code, and partly in preparation for removing the artificial requirement for the first three vertices of a panel to be non-collinear for calculating its normal. Also optimized a few other related areas that I noticed along the way. No functional changes yet. Just refactoring in preparation.
=> Refactor normal calculations and related areas

core/src/main/java/com/vzome/api/Vector.java, core/src/main/java/com/vzome/core/algebra/AlgebraicVectors.java, core/src/main/java/com/vzome/core/commands/CommandPolygon.java, core/src/main/java/com/vzome/core/construction/PerpendicularLine.java, core/src/main/java/com/vzome/core/construction/PlaneExtensionOfPolygon.java, core/src/main/java/com/vzome/core/construction/Polygon.java, core/src/main/java/com/vzome/core/construction/PolygonFromVertices.java, core/src/main/java/com/vzome/core/construction/PolygonRotated4D.java, core/src/main/java/com/vzome/core/construction/PolygonVertex.java, core/src/main/java/com/vzome/core/construction/Segment.java, core/src/main/java/com/vzome/core/construction/SegmentCrossProduct.java, core/src/main/java/com/vzome/core/construction/TransformedPolygon.java, core/src/main/java/com/vzome/core/editor/DocumentModel.java, core/src/main/java/com/vzome/core/editor/ShowNormals.java, core/src/main/java/com/vzome/core/editor/ShowVertices.java, core/src/main/java/com/vzome/core/editor/Symmetry4d.java, core/src/main/java/com/vzome/core/math/Polyhedron.java, core/src/main/java/com/vzome/core/math/symmetry/AbstractSymmetry.java, core/src/main/java/com/vzome/core/math/symmetry/Direction.java, core/src/main/java/com/vzome/core/model/RealizedModel.java, core/src/main/java/com/vzome/core/parts/DefaultStrutGeometry.java, core/src/main/java/com/vzome/core/parts/FastDefaultStrutGeometry.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/StrutBuilderController.java, desktop/src/main/java/org/vorthmann/zome/render/java3d/Java3dFactory.java
resolved a conflict in Java3dFactory
=> merge David's normals branch

core/src/main/java/com/vzome/core/editor/DocumentModel.java, core/src/main/java/com/vzome/core/exporters/Exporter3d.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/MeasureController.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java, desktop/src/main/java/org/vorthmann/zome/ui/MeasurePanel.java, desktop/src/main/java/org/vorthmann/zome/ui/PartsPanel.java
Also added a light gray background to both tables.
Currently, the only measures computed are dihedral angle between panels,
the angle between struts, and the distance between balls.
=> Added "measure" tab with angle and distance measures

desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/Java2dSnapshotController.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java, desktop/src/main/java/org/vorthmann/zome/ui/Snapshot2dFrame.java
The auto-export can be any 2D exporter registered with the
Application.
=> The save.exports property now supports export2d.*

desktop/src/main/java/org/vorthmann/zome/ui/ModelPanel.java
The toolbar buttons were not using the SymmetryController, and
the icosasymm buttons had the wrong action string.
=> Fixed some broken tools in the legacy toolbar

core/src/main/java/com/vzome/core/render/RenderedModel.java, desktop/src/main/java/org/vorthmann/zome/app/impl/MeasureController.java
* Handle floating point rounding errors for acos() calculation resulting in NaN
* Include the number of selected balls, struts and panels in MeasureController
* MeasureController Map preserves insertion order rather than auto-sorting
* When two disconnected struts are selected, show if they are coplanar or skew
* Show applicable measures when only one item is selected
=> Enhancements and bug fix for MeasureController

desktop/src/main/java/org/vorthmann/zome/app/impl/ApplicationController.java
Allowing redirects, and removed the overly-strict check for ".vZome" at
the end of the URL.
Also reformatted!
=> Simple fix for HTTP redirects

core/src/main/java/com/vzome/core/algebra/AlgebraicField.java, core/src/main/java/com/vzome/core/algebra/BigRational.java, core/src/test/java/quickhull3d/QuickHull3D.java, desktop/src/main/java/org/vorthmann/ui/DefaultController.java
I'll be out of town for nearly 2 weeks. Just wanted to get this minor PR to you before I leave. This is the replacement PR for the one I canceled a few weeks ago.
=> Clean up Java compiler warnings

desktop/src/main/java/com/vzome/desktop/controller/CameraController.java, desktop/src/main/java/org/vorthmann/zome/ui/CameraControlPanel.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
No more menu item.
Also, the CameraControlPanel.java file is now in the UI package with
everything else.
=> Made a view checkbox for drawOutlines

desktop/src/main/resources/com/vzome/starters/symmetry/icosahedral/starter.vZome, desktop/src/main/resources/com/vzome/starters/symmetry/octahedral/sqrt2/starter.vZome, desktop/src/main/resources/com/vzome/starters/symmetry/octahedral/starter.vZome, desktop/src/main/resources/com/vzome/starters/symmetry/tetrahedral/starter.vZome
Added the Coxeter domain balls to all.
Octahedral now has blue-green strut scaffolding.
Tetrahedral now has an icosahedron generator.
=> Improvements to the symmetry starters

core/src/main/java/com/vzome/core/editor/ConvexHull3d.java, core/src/regression/files/2019/07-Jul/09-David-3DConvexHullModes/3DConvexHullModes.vZome, core/src/regression/files/sniff-test.vZome-files, desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
Add a new regression file using the two new modes
=> Add optional "noPanels and "onlyPanels" modes to ConvexHull3d

core/src/main/java/com/vzome/core/editor/LoadVEF.java, core/src/main/java/com/vzome/core/math/QuaternionProjection.java
Also reformatted LoadVEF and QuaternionProjection.
=> Fixed serialization bug for LoadVEF

desktop/src/main/java/org/vorthmann/zome/render/java3d/Java3dSceneGraph.java, desktop/src/main/resources/org/vorthmann/zome/app/defaultPrefs.properties
Also, I corrected the initial lighting settings to match the pref.
=> Default for "outline.geometry" is now false

core/src/main/java/com/vzome/core/algebra/VefVectorExporter.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/PolytopesController.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java
It works by just using the current values in the PolytopesController,
and emulating what the Polytope4d command would do.  It does NOT do any
projection to 3d, and it exports the rotated vertices after quaternion
multiplication.
Also reformatted DocumentController and parts of DocumentFrame.
=> Added export4dPolytope command

core/src/main/java/com/vzome/core/editor/LoadVEF.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/PolytopesController.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java, desktop/src/main/java/org/vorthmann/zome/ui/PolytopesDialog.java, desktop/src/main/java/org/vorthmann/zome/ui/QuaternionPanel.java, desktop/src/main/java/org/vorthmann/zome/ui/VefImportDialog.java
The "import scale" dialog now includes a quaternion config panel.
The state is in the QuaternionController, shared with the 4D polytopes dialog.
=> Quaternion config for VEF import

desktop/platform/windows/README.md
No content change... just fixed markdown formatting
=> Update markup in README.md so it renders correctly on github.

desktop/src/test/java/com/vzome/controller/ControllerTesting.java
Avoid null source assertion which was causing several tests to fail.
=> Fix failing controller tests

core/src/main/java/com/vzome/core/construction/PolygonPolygonProjectionToSegment.java, core/src/main/java/com/vzome/core/edits/PanelPanelIntersection.java, core/src/regression/files/2019/09-Sep/24-David-PanelPanelIntersection/PanelPanelIntersection.vZome, core/src/regression/files/sniff-test.vZome-files, desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
Add new PanelPanelIntersection command
=> Panel-Panel Intersection

core/src/main/java/com/vzome/core/edits/ColorManifestations.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
The setItemColor command always initializes the JColorChooser with the
lastObjectColor, and updates it before returning.
Also added a keyboard equivalent for setItemColor.
=> Remembering lastObjectColor in DocumentController

core/src/main/java/com/vzome/core/tools/ProjectionTool.java
Now testing for the degenerate case where the projection line is
parallel to the projection plane.
=> Fixing bug in projection tool

core/src/main/java/com/vzome/core/tools/ProjectionTool.java
By adding the line test, I inadvertently made the line required.
=> Fixing the last fix to the projection tool

desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, desktop/src/main/java/org/vorthmann/zome/render/jogl/JoglRenderingViewer.java, desktop/src/main/java/org/vorthmann/zome/render/jogl/JoglScene.java
=> Fix image capture on Windows

core/src/main/java/com/vzome/core/render/ShapeAndInstances.java, core/src/main/java/com/vzome/core/render/SymmetryRendering.java, desktop/src/main/java/org/vorthmann/zome/render/jogl/NearestPicker.java, desktop/src/test/java/org/vorthmann/zome/render/jogl/View3dActivity.java
I still cannot quite believe how quickly the CPU can compute all those
intersections.
The current todo list:
* 2d drag
* correct panel lighting
* implement transparency
* implement drawNormals, showFrameLabels, showIcosahedralLabels
=> Strut picking implemented

core/src/main/java/com/vzome/core/render/ShapeAndInstances.java, desktop/src/main/java/org/vorthmann/zome/render/jogl/NearestPicker.java
This is more accurate that the AABBox implementation, and the performance
seems fine.
=> Switched to triangle picking for balls

core/src/main/java/com/vzome/core/editor/DocumentModel.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java
This fix should be cherry-picked into the vzome-6 maintenance branch as well.
=> Thumbnails now render when opening a model with articles

core/src/main/java/com/vzome/core/kinds/DefaultFieldApplication.java, core/src/main/java/com/vzome/core/kinds/GoldenFieldApplication.java, core/src/main/java/com/vzome/core/kinds/HeptagonFieldApplication.java, core/src/main/java/com/vzome/core/kinds/SnubDodecFieldApplication.java, core/src/main/java/com/vzome/fields/sqrtphi/SqrtPhiFieldApplication.java
This is not a functional change, just refactoring common code to simplify the integration of the parameterizedFields branch later.
=> Refactor common code in registerToolFactories()

core/src/main/java/com/vzome/core/exporters2d/PostScriptExporter.java
Not sure what motivated this, but it should be harmless.
=> Recovering an old fix to the PS exporter

core/src/main/java/com/vzome/core/render/ShapeAndInstances.java, core/src/main/java/com/vzome/opengl/OpenGlShim.java, core/src/main/java/com/vzome/opengl/SolidRenderer.java, desktop/src/main/java/org/vorthmann/zome/render/jogl/JoglOpenGlShim.java
The problem was simply backface culling was not enabled.
The current todo list:
* implement transparency
* optimize trackball in main view: cheaper exploratory pick, balls only
* implement drawNormals, showFrameLabels, showIcosahedralLabels
=> Fixed the panel rendering defect

core/src/main/java/com/vzome/core/render/ShapeAndInstances.java, core/src/main/java/com/vzome/core/render/TransparentRendering.java, core/src/main/java/com/vzome/opengl/OpenGlShim.java, core/src/main/java/com/vzome/opengl/SolidRenderer.java, desktop/src/main/java/org/vorthmann/zome/render/jogl/JoglOpenGlShim.java
Rendering order still needs to be handled to make things look better.
=> Transparency partially fixed

core/src/main/java/com/vzome/opengl/OpenGlShim.java, desktop/src/main/java/org/vorthmann/zome/render/jogl/JoglFactory.java, desktop/src/main/java/org/vorthmann/zome/render/jogl/JoglOpenGlShim.java
See https://jogamp.org/jogl-demos/src/demos/multisample/Multisample.java
=> Implemented Multi-sample Anti-aliasing

core/src/main/java/com/vzome/core/tools/BookmarkTool.java, desktop/src/main/java/org/vorthmann/zome/ui/ModelPanel.java, desktop/src/main/java/org/vorthmann/zome/ui/ToolConfigDialog.java
I also reformatted BookmarkTool, and made sure that the bookmarked items
are added as parameters, so the "show and select parameters" button works.
=> Bookmark tools are now configurable

core/src/main/java/com/vzome/core/editor/Application.java, core/src/main/java/com/vzome/core/editor/EditHistory.java, core/src/main/java/com/vzome/xml/LocationAnnotator.java, core/src/main/java/com/vzome/xml/LocationData.java
Using a solution from:
http://javacoalface.blogspot.com/2011/04/line-and-column-numbers-in-xml-dom.html
I had to make just one change, to uncomment the namespace-awareness for
the SAX parser.
=> Capturing line numbers during XML parse

core/src/main/java/com/vzome/core/editor/EditHistory.java, desktop/src/main/java/com/vzome/dap/DapAdapter.java, desktop/src/main/java/com/vzome/desktop/controller/ThumbnailRendererImpl.java
File paths are now OS independent and a few related bugs I found along the way are fixed.
=> Fixed a few DapAdapter related bugs and log the DapAdapter responses

core/src/main/java/com/vzome/core/algebra/AlgebraicField.java, core/src/main/java/com/vzome/core/algebra/AlgebraicNumber.java, core/src/main/java/com/vzome/core/math/VefParser.java, core/src/main/java/com/vzome/fields/sqrtphi/SqrtPhiField.java, core/src/test/java/com/vzome/core/algebra/AlgebraicNumberTest.java, core/src/test/java/com/vzome/core/kinds/FieldApplicationTest.java
See the comments for a description of the problem and the solution, especially the comments in the second commit and in the new test case.
I know you're going to be out of town this weekend. I'll be available to discuss this PR most evenings this week if you get a chance and want to look at it before you leave.
Thanks
=> Safer ways to create AlgebraicNumbers

core/src/main/java/com/vzome/core/algebra/AlgebraicVector.java, core/src/main/java/com/vzome/core/kinds/SnubDodecFieldApplication.java, core/src/main/resources/com/vzome/core/editor/defaultPrefs.properties, core/src/regression/files/2020/03-Mar/06-David-SnubDodec/SnubDodecFromConvexHull.vZome, core/src/regression/files/sniff-test.vZome-files, core/src/test/java/com/vzome/core/kinds/FieldApplicationTest.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java
* See the description of the two new directions in individual commit comments.
* Added a new regression file and another unit test.
* Made a few other trivial tweaks, each as its own commit, just for clarity.
=> Add two missing fundamental directions to SnubDodec icosahedral symmetry

desktop/src/main/java/org/vorthmann/zome/app/impl/MeasureController.java
* Show ratio of the lengths of two selected struts as well as the reciprocal of that ratio.
* Show decimal approximation of the ratio when lengths are not equal.
* Also show the exact ratio as an AlgebraicNumber when struts are in the same orbit.
=> Show the ratio of two strut lengths on the MeasureController

core/src/main/java/com/vzome/core/editor/LessonModel.java
The bug was introduced in commit 5f70481bed5e5b614db9f6b7765079cebdbb561c.
=> Fix for the exception on creation of first lesson page

.gitignore, core/src/main/java/com/vzome/core/editor/Application.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/PickingController.java, desktop/src/main/java/org/vorthmann/zome/ui/ModelPanel.java
I found this helpful in my new SnubCubeField, so I thought I'd separate it into its own PR. Comments in DocumentController explain the use case. Most notably, the new command is intentionally implemented in desktop only, not in core, though the second commit is a trivial unrelated improvement to error reporting in core.
=> A simple tool to help developing new directions

core/src/test/java/com/vzome/core/kinds/FieldApplicationTest.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/PickingController.java, desktop/src/main/java/org/vorthmann/zome/ui/ModelPanel.java
* Similar to CreateStrutPrototype command.
* Add a new test case to identify the Directions that have different zone vectors between the two commands.
* Found that getPrototype( ) != getAxis(Plus,0).normal( )
only for these directions:
synestructics magenta // effectively the same as octahedral green
octahedral green
icosahedral green
icosahedral orange
icosahedral black
=> Add new CreateStrutAxisPlus0 command

core/src/main/java/com/vzome/fields/heptagon/HeptagonalAntiprismSymmetry.java, core/src/test/java/com/vzome/core/kinds/FieldApplicationTest.java
It only adds the new green direction and tweaks one orbit triangle vector length as we discussed. It does not modify the heptagonal antiprism trackball at all.
=> This is a substitute for the previous heptagon-yellow PR.

core/src/main/java/com/vzome/fields/heptagon/HeptagonalAntiprismSymmetry.java
* Removed 2 unnecessary calls to setDotLocation().
* I still want to make a corresponding green VEF strut model once picking is fixed.
=> Correct the length of heptagonal antiprism green strut

core/src/main/java/com/vzome/core/model/ColoredMeshJson.java, core/src/main/java/com/vzome/core/model/SimpleMeshJson.java
All 2020 files open successfully.
=> Really fixed the broken mesh import commands.

desktop/src/main/java/org/vorthmann/zome/ui/OrbitPanel.java
The "single" checkbox was not getting updated.
=> Corrected build-with-this defect

.gitignore, cheerpj/build.bash, cheerpj/index.html, desktop/src/main/java/org/vorthmann/zome/app/impl/ApplicationController.java
This is so that I can try out the controller with CheerpJ, a tool for compiling Java to WASM/Javascript:
https://www.leaningtech.com/pages/cheerpj.html
The JARs all seem to compile fine (except for JOGL dependencies that I'm not worrying
about), and the code runs as well, at least until the Gist URL seems to
return empty data.
See the build.bash under cheerpj to test.  It is tested on a Mac; it
assumes you have installed CheerpJ and done the "control-open" trick on
all the binaries to get them to run despite not being signed.
=> Testing CheerpJ

client/package-lock.json, client/package.json, client/public/index.html, client/src/bundles/camera.js, client/src/bundles/jre.js, client/src/bundles/lighting.js, client/src/bundles/vzomejava.js, client/src/components/modelcanvas-three.js, client/src/index.js, core/src/main/java/com/vzome/core/model/Color.java, core/src/main/java/com/vzome/core/viewing/Camera.java, core/src/main/java/com/vzome/core/viewing/Lights.java, desktop/src/main/java/com/vzome/desktop/controller/CameraController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/JsonClientShim.java
Lots of improvements to the online reader, with a few Java changes motivated by them.
=> Copy camera

client/src/components/modelcanvas-three.js, client/src/models/dodecahedron/index.js, core/src/main/java/com/vzome/core/exporters/PdbExporter.java, core/src/main/java/com/vzome/core/exporters2d/Java2dExporter.java, core/src/main/java/com/vzome/core/math/RealVector.java, core/src/main/java/com/vzome/core/render/JsonMapper.java, core/src/main/java/com/vzome/core/render/RenderedManifestation.java, core/src/main/java/com/vzome/core/render/RenderedModel.java, core/src/main/java/com/vzome/core/render/ShapeAndInstances.java, core/src/main/java/com/vzome/core/render/SymmetryRendering.java, desktop/src/main/java/com/vzome/desktop/controller/JsonClientRendering.java, desktop/src/main/java/org/vorthmann/zome/app/impl/JsonClientShim.java, desktop/src/main/java/org/vorthmann/zome/app/impl/SymmetrySnapper.java, server/src/main/java/com/vzome/server/ControllerWebSocket.java
Directional lighting is working, as is batch rendering.
=> Batch render

client/src/bundles/camera.js, client/src/components/modelcanvas-three.js
Also, I made a slight optimization of Lighting (I think).
=> Fixed camera lookAt and FOV

client/src/bundles/files.js, client/src/bundles/jre.js, client/src/bundles/vzomejava.js, client/src/components/exporter.js, client/src/index.js, desktop/src/main/java/com/vzome/cheerpj/JavascriptClientShim.java, desktop/src/main/java/org/vorthmann/ui/DefaultController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/ApplicationController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, desktop/src/main/java/org/vorthmann/zome/app/impl/JsonClientShim.java, desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java, server/src/main/java/com/vzome/server/ControllerWebSocket.java
Online reader now has a nice download experience for export DAE.
In support of that, I refactored the Platform and Runtime usage out of the controllers, on the Java side.
=> Platform ui

client/src/App.css, client/src/App.js, client/src/bundles/camera.js
The problem was the style of the HTML body.
I also implemented a FOV that respects the window state.
=> Corrected the canvas height

client/src/index.js, core/src/main/java/com/vzome/core/render/RenderedManifestation.java, core/src/main/java/com/vzome/core/viewing/Lights.java, desktop/src/main/java/org/vorthmann/zome/render/jogl/JoglRenderingViewer.java
Color was being serialized with defaults, and it is recursive due to
getPastel.  Also, RM was serializing getOrbitSource.
=> Defects in Jackson serialization fixed

build-client.bash
Also using "source" for cheerpj.bash, so main script waits correctly.
=> Adding banners to build-client.bash

client/src/App.css, client/src/components/editmenu.js
I also increased the popup size, so it is not so annoying.
=> Made the edit menu visible in the upper left

core/src/main/java/com/vzome/core/algebra/AlgebraicMatrix.java, core/src/main/java/com/vzome/core/edits/ImportMesh.java, core/src/main/java/com/vzome/core/edits/RunZomodScript.java, core/src/main/java/com/vzome/core/tools/TransformationTool.java, core/src/main/java/com/vzome/core/zomic/parser/Parser.java, core/src/main/java/com/vzome/core/zomic/parser/ZomicParser.java, core/src/main/java/com/vzome/core/zomod/parser/Parser.java, core/src/main/java/com/vzome/core/zomod/parser/ZomodLexer.java, core/src/main/java/com/vzome/core/zomod/parser/ZomodParser.java
My regression suite was running against the same commit since March, so several regressions had crept in since then.  This addresses them all.
=> Fix regressions

client/src/bundles/jsweet.js, core/src/jsweet/java/com/vzome/jsweet/JsSelection.java
I can open 2020/11-Nov/02-JohnHall-phage/Phage.vZome!
=> Default bookmark tool is working

client/src/bundles/index.js, client/src/components/about.js, client/src/components/logo.js
- logo now links to main site
- about now links to the download page
- CheerpJ mode is available as "profile=tortoise"
=> Link improvements

client/src/bundles/files.js, client/src/components/webloader.js
Thanks to Nan, who found https://cors-anywhere.herokuapp.com.
=> Using CORS proxy

client/src/bundles/jsweet.js
I had skipped over an essential step when duplicating DocumentModel
constructor logic related to symmetry systems.
=> Fix for tool factories

desktop/platform/mac/build.gradle, desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
I also updated the help links to include vZome Online, and added Nan Ma
to the about dialog as a contributor.
=> Allowed java.ext.dirs so I can use SSL for API calls

.gitignore, client/package-lock.json, client/package.json, core/build.gradle, core/src/main/java/com/vzome/core/editor/Application.java, core/src/main/java/com/vzome/core/kinds/RootTwoFieldApplication.java, react-library/package.json, react-library/playground/public/models/jk-Deltoid.vZome, react-library/playground/src/index.js, react-library/src/core/legacyjava.js, react-library/src/fields/root2.js, react-library/src/index.js, react-library/src/jsweet/bundle.js, react-library/src/resources/com/vzome/core/parts/index.js, react-library/src/resources/com/vzome/core/parts/rootTwo/index.js, react-library/src/resources/com/vzome/core/parts/rootTwoBig/index.js, react-library/src/resources/com/vzome/core/parts/rootTwoSmall/index.js
This required a small Java code change; see core/editor/Application.java.
It follows the pattern of GoldenFieldApplication.
=> Enabled rootTwo field for vZome Online

core/src/main/java/com/vzome/core/exporters/OffExporter.java
OFF export now providing 16 digits after the decimal.
=> Fixes #313

core/src/main/java/com/vzome/core/render/RenderedManifestation.java, core/src/test/java/com/vzome/core/kinds/FieldApplicationTest.java
Also, a fix for the test broken in the last commit.
=> Fix for 2D panel rendering bug

react-library/package-lock.json, react-library/package.json, react-library/src/components/urlviewer.js
=> Added download button to UrlViewer

online/package-lock.json, online/package.json, react-library/package-lock.json, react-library/package.json
=> Updated react-vzome to 0.9.8

core/src/main/java/com/vzome/core/edits/AffineHeptagon.java, online/package.json, react-library/package-lock.json, react-library/package.json, react-library/public/models/hept-test.vZome, react-library/src/core/legacyjava.js
I was failing to embed... an easy fix.
I also remove the odd class.cast constructs from AffineHeptagon.
=> Fixed heptagon antiprism rendering

core/src/main/java/com/vzome/core/algebra/AbstractAlgebraicField.java, core/src/main/java/com/vzome/core/algebra/AlgebraicNumberImpl.java, core/src/test/java/com/vzome/core/kinds/FieldApplicationTest.java, core/src/test/java/com/vzome/core/render/RenderedModelTest.java, desktop/src/main/java/org/vorthmann/zome/app/impl/MeasureController.java, desktop/src/main/java/org/vorthmann/zome/ui/PartsPanel.java, desktop/src/test/java/org/vorthmann/zome/app/impl/LengthPanelControllersTest.java
Also...
* Context menus on parts menu work again for selecting and deselecting parts.
* Fixed several broken unit tests using HeptagonField.
* Clarify direction names in measure panel.
* Incorporated embedding in some measure panel calculations.
* Other minor tweaks as listed in commit comments.
=> Fix parts panel rendering problem - Issue #309

core/src/main/java/com/vzome/core/math/Polyhedron.java, online/package-lock.json, online/package.json, online/src/components/debugger.jsx, react-library/package-lock.json, react-library/package.json
Also corrected scrolling in the online debugger
=> Fixed a transpile bug in shape resolution

core/src/main/java/com/vzome/core/editor/Application.java, core/src/main/java/com/vzome/core/kinds/RootThreeFieldApplication.java, online/package-lock.json, online/package.json, react-library/package-lock.json, react-library/package.json, react-library/src/core/legacyjava.js, react-library/src/fields/common.js, react-library/src/fields/golden.js, react-library/src/fields/heptagon.js, react-library/src/fields/root2.js, react-library/src/fields/root3.js, react-library/src/index.js
Also, common code has been factored out of all the fields.
=> Now supporting rootThree field in vZome Online

core/src/test/java/com/vzome/core/kinds/FieldApplicationTest.java
=> Fix root3 unit test

core/build.gradle, online/src/bundles/dbugger.js, online/src/components/debugger.jsx, react-library/src/core/legacyjava.js
Also, I added the debugger command details view.
It is still very primitive, just showing outerHTML.
=> Fixed some stinkers in the rootThree support

online/src/App.jsx, online/src/BHallBasic.jsx, online/src/components/appbar.jsx, online/src/components/debugger.jsx
I'm pushing this as-is, because I haven't found a way around the maxHeight
on debuggerSource, and I need to ask for help.
=> Hacky debugger layout CSS fix

desktop/src/main/java/com/vzome/desktop/controller/CameraController.java, desktop/src/main/java/com/vzome/desktop/controller/ThumbnailRendererImpl.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java
All CameraControllers are created from the DocumentController, and it was
already using maxOrientations.
=> Fixed #338

core/src/main/java/com/vzome/core/tools/AxialSymmetryToolFactory.java
This is still just a workaround for creating more unique throwaway tool
factories.  The ideal solution would be to use the real tool factories,
and to use symmetry names to make predefined tools unique automatically.
=> Infrastructure for more unique predefined tool names.

desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
Added links for Twitter and Discord, and the "how to share" video.
I also renamed some entries in the Help menu, for more clarity.
=> Added "share gist" menu item, and more help links

core/src/jsweet/java/com/vzome/jsweet/JsAlgebraicField.java, core/src/jsweet/java/com/vzome/jsweet/JsAlgebraicNumber.java, online/package-lock.json, online/package.json, online/src/bundles/planes.js, react-library/package-lock.json, react-library/package.json, react-library/src/core/legacyjava.js, react-library/src/fields/common.js, react-library/src/fields/golden.js, react-library/src/fields/heptagon.js, react-library/src/fields/root2.js, react-library/src/fields/root3.js
As part of this, I rationalized the "native" AF methods for creating ANs.
Now everything funnels through either createRational() or
createRationalFromPairs().
=> Added arbitrary-precision integers (BigInt) in vZome Online

core/src/jsweet/java/java/beans/PropertyChangeListener.java, core/src/main/java/com/vzome/core/math/symmetry/QuaternionicSymmetry.java, core/src/main/java/com/vzome/core/viewing/ExportedVEFShapes.java, core/src/main/java/com/vzome/xml/ResourceLoader.java, react-library/src/core/legacyjava.js
Two changes, getting the JSweet transpile errors down to just 96
=> 0 cleaner transpile

core/src/main/java/com/vzome/core/editor/Application.java, core/src/main/java/com/vzome/core/editor/DocumentModel.java, core/src/test/java/com/vzome/core/exporters/ExporterTest.java, desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java
The "export.partgeom" command was resulting in a vanilla VefExporter.
=> Fixed broken PartGeometryExporter

desktop/src/main/java/org/vorthmann/zome/app/impl/ApplicationController.java, desktop/src/main/resources/org/vorthmann/zome/app/dodecagonal-update-WIP.vZome, desktop/src/main/resources/org/vorthmann/zome/app/heptagonal antiprism.vZome, desktop/src/main/resources/org/vorthmann/zome/app/icosahedral-vef.vZome, desktop/src/main/resources/org/vorthmann/zome/app/octahedral-vef.vZome
As part of this, I removed the restriction that only rendered panels for
trackball models.
=> Added orientation hints to trackball models

desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
I also reorganized the Help menu again.
=> Modified the link for "Sharing vZome Files Online" help

desktop/src/main/java/org/vorthmann/zome/ui/ShareDialog.java
I'm no longer fully encoding the url query arguments, so that the vZome
Online URLs are more readable.  As long as the folder name is doubly
encoded, and the file name is encoded, this works fine... "/" is a fixed
point under URL decode.
=> Simplified the URL encoding for cleaner URLs

core/src/main/java/com/vzome/core/math/symmetry/Permutation.java
Replaced hard coded value in loop
=> Fix: Full rotation tool doesn't work with PolygonField > 20

online/package-lock.json, online/package.json, react-library/package-lock.json, react-library/package.json, react-library/rollup.config.js
I also added @rollup/plugin-json to handle the (as yet unused) shapes
JSON files.
=> Bumped React component version

desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
Removed an unrelated unnecessary cast
=> Fix NPE opening direction config dialog for antiprism symmetry

desktop/src/main/java/org/vorthmann/zome/app/impl/ApplicationController.java
Now, vZome will only store its own data in ~/.vZome-config.properties,
which is a hidden file by design.
User-editable preferences should be kept in one of these places, in order
of preference:
~/Library/Preferences/vZome/vZome.preferences   (on Mac)
~/vZome-Preferences/vZome.preferences           (on Windows and Linux)
~/vZome.preferences
~/.vZome.prefs
That is, new users should use one of the top two.
Existing values for saw.welcome and githubAccessToken still in the old
prefs file will still work, but the new file will take precedence once it
exists.
=> Fixes #416

online/package-lock.json, online/package.json, react-library/package-lock.json, react-library/package.json, react-library/src/components/buildplane.jsx, react-library/src/components/designcanvas.jsx
Finally got past the breaking changes in three.js 0.125!
No new APIs used, but I had to remove useResource calls, per:
https://github.com/pmndrs/react-three-fiber/blob/master/markdown/changelog.md#removal-of-useresource
=> Upgraded three.js, r3f, and drei

online/src/bundles/designs.js, react-library/README.md
I also made a couple of cleanup changes in online.
=> Better documentation for react-library dev workflow

core/src/main/java/com/vzome/core/algebra/HeptagonField.java, core/src/main/java/com/vzome/core/algebra/SnubDodecField.java
Some valid args returned the wrong value and other valid args threw IllegalArgumentException
=> Fix getIrrational() in SnubDodecField and HeptagonField

online/src/app/App.jsx, online/src/app/components/folder.jsx
Also, I made an attempt at fixing the path to the built-in models.
=> Fixed missing spinner for legacy preview mode in the app

online/src/ui/viewer/store.js, online/src/wc/vzome-viewer.js, online/src/worker/vzome-worker-static.js
Once again, Lucas saves the day:
https://github.com/evanw/esbuild/issues/312#issuecomment-1025066671
=> Fixing CORS issue with worker

online/src/app/App.jsx, online/src/app/Article.jsx, online/src/app/BHallBasic.jsx, online/src/app/components/folder.jsx
I also corrected the handling of relative URL query params for the app,
and fixed the truncated 5-cell URL to be absolute.
=> Fixed bhall and article apps

online/src/app/Browser.jsx, online/src/app/components/browser.jsx, online/src/app/index.jsx
No way to choose the user except by the `?user=...` query parameter.
=> GitHub browser UI

online/public/index.html, online/src/app/index.jsx
Also, hopefully fixing the broken favicon.
=> Fixing the app routing

desktop/src/main/java/org/vorthmann/zome/app/impl/ApplicationController.java, desktop/src/main/java/org/vorthmann/zome/ui/ShareDialog.java, desktop/src/main/resources/org/vorthmann/zome/app/defaultPrefs.properties, desktop/src/main/resources/org/vorthmann/zome/ui/githubPostTemplate.md, desktop/src/main/resources/org/vorthmann/zome/ui/githubReadmeNoPostTemplate.md
The state of the checkboxes is sticky across files and across sessions.
=> Sharing now presents a configuration dialog

ideas-today.txt, online/src/app/bhall/basic/index.jsx, online/src/app/fivecell/index.jsx
Now that the URLs are resolved from the worker, we have to make sure they
are first made absolute relative to the app URL.
=> Fixing relative URLs for fivecell and bhall apps

online/src/app/components/folder.jsx, online/src/ui/viewer/store.js, online/src/worker/legacy/edit.js, online/src/worker/legacy/jsweet2js.js, online/src/worker/vzome-worker-static.js
I added the missing openDesignFile action to the store, in the process.
=> Fixed missing debug capability for local files

online/src/ui/viewer/index.jsx
This is an alternative to fullscreen mode, which is not supported on
iPhones.
I may want to actually adopt a hybrid approach.  I have saved the true
fullscreen mode changes on another branch.
=> Full viewport mode

.gitignore, online/src/worker/legacy/jsweet2js.js
This was causing problems with ConvexHull2D.
=> Adding missing comparisons for JavaAlgebraicNumber

online/src/ui/viewer/designcanvas.jsx
The controlled camera is much better so that I can see the page author's
intended view, or close to it.
=> Restored the perspective camera for VR mode

online/src/worker/legacy/js2jsweet.js, online/src/worker/legacy/logging.js
To enable a logger, add a line in /online/src/worker/legacy/logging.js
=> Enabled JDK logging in the web worker

core/src/main/java/com/vzome/core/editor/DocumentModel.java
=> Handle debugging more than 8 snapshots with lastStickyEdit = -1

core/src/main/java/com/vzome/core/edits/SelectAll.java, desktop/src/main/java/com/vzome/desktop/awt/DocumentController.java
Implement origin-last selection order for the SelectAll command
=> Select origin last

desktop/build.gradle, desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java
Also correct a typo on the -Xmx JVM arg
=> Fix maximized initial window state behavior on Windows with Java 17

core/src/main/java/com/vzome/core/tools/TransformationTool.java
The change was an attempted optimization anyway.
=> Reverted TransformationTool change that broke color copying

build.gradle, server/build.gradle
With newer Gradle, "transitive soup" dependencies don't work.
I also remove some unnecessary insecure repos, adding HTTPS.
=> Corrected dependencies for server project

online/src/app/bhall/basic/index.jsx, online/src/app/browser/index.jsx, online/src/app/classic/index.jsx, online/src/app/components/about.jsx, online/src/app/components/appbar.jsx, online/src/app/fivecell/index.jsx, online/src/app/index.jsx
I parameterized the About and VZomeAppBar components.
=> Improvements to "about" content for online apps

online/src/app/browser/browser.jsx, online/src/app/browser/github.js, online/src/app/classic/components/toolbars.jsx
I've formatted the list entries to highlight file names better, and added
a button to copy the URL to the clipboard.
I also improved the initial layout for the classic factory bar, so that it
does not generate a scrollbar for the page before the icons are added.
=> Improvements to the GitHub browser app

online/public/App.css, online/public/classic/classic.css, online/public/classic/index.html, online/src/app/classic/classic.jsx, online/src/app/classic/components/camera.jsx, online/src/app/classic/components/toolbars.jsx, online/src/app/classic/orbit-panel.jsx, online/src/worker/legacy/controllers.js, online/src/worker/legacy/core.js, online/src/worker/vzome-worker-static.js
I've added the bookmarkController, but both the bookmarks bar and the toolbar
are not populated correctly, since there is no list property for either.  Instead,
the desktop UI just listens for "tool.added" PCEs.  I have set up a PCL on the
worker side that maps these into change events for a synthetic list property,
but I cannot test it until I have everything hooked up.
I've also cleaned up React warnings, adding keys and changing to className,
and I gave Classic its own stylesheet.
=> Adding more components to Classic online

online/src/app/classic/classic.jsx, online/src/app/classic/components/length.jsx, online/src/app/classic/components/orbit-panel.jsx, online/src/app/classic/controller-hooks.js, online/src/ui/viewer/store.js
OrbitPanel is still working, and LengthPanel gets its color updated.
Also, I've fixed the requestControllerProperty cascade, so everything is working
a lot faster!
=> WIP Encapsulated StrutBuildPanel

desktop/src/main/java/com/vzome/desktop/awt/CameraGraphicsController.java, desktop/src/main/java/com/vzome/desktop/awt/DocumentController.java
Paul H asked for this.  Accidental rotations can be a big problem when
working on very large models.
=> Added no.main.view.trackball preference

online/src/worker/legacy/core.js
Files from any field will generally open now, but there is still one
defect because the old build plane state is not cleared out when a
new design is loaded, so there can be an error if the old plane was
"red" and the new symmetry is octahedral, for example.
=> WIP Generalized the build plane derivation for any field

online/public/buildplane/icons/maskable_icon_x128 (1).png, online/public/buildplane/icons/maskable_icon_x192 (1).png, online/public/buildplane/icons/maskable_icon_x384 (1).png, online/public/buildplane/icons/maskable_icon_x48 (1).png, online/public/buildplane/icons/maskable_icon_x512 (1).png, online/public/buildplane/icons/maskable_icon_x72 (1).png, online/public/buildplane/icons/maskable_icon_x96 (1).png, online/public/buildplane/manifest.json, online/src/app/components/about.jsx
I also added custom icons for the buildplane PWA.
=> Added revision number to about dialog

online/src/app/classic/classic.jsx
Older files had no sceneModel or backgroundColor.
=> Fix parsing for vZome 2.1 files

desktop/src/test/java/org/vorthmann/zome/render/jogl/View3dActivity.java
Add comments about the "add-exports" JVM args required to use JOGL in JAVA 17.
=> Add default URL to View3dActivity

developer-docs/regression-testing.md, online/public/test/index.html, online/public/test/regression.html, online/src/wc/vzome-viewer.js
The viewer uses `show-scenes`, so it will require vZome interpretation
for older files.  For newer ones, the preview will suffice.
I have not waited long enough to see if it successfully views all of JK's files;
some of the 60-gon field files take a really long time.
=> Revived web component regression testing

desktop/src/main/java/com/vzome/desktop/controller/CameraController.java
The trackball model scene was not getting reset.
=> Fixed issue with symmetry model overlay

desktop/src/main/java/com/vzome/desktop/api/Controller.java, desktop/src/main/java/com/vzome/desktop/controller/MeasureController.java
variable name 'arguments' is not allowed.
variable name 'in' is not allowed
=> Avoid some simple jsweet compile warnings

online/src/worker/java/com/vzome/jsweet/JsAlgebraicField.java, online/src/worker/legacy/core.js, online/src/worker/legacy/parser.js, online/src/worker/vzome-worker-static.js
I also added the loadDesign error.message to the alert sent back
from the worker, for example when a vZome file requires Zomic.
=> Bug fixes for loading very old vZome files

desktop/src/main/java/com/vzome/desktop/controller/PolytopesController.java, online/src/app/classic/classic.jsx, online/src/app/classic/components/polytopes.jsx, online/src/app/classic/menus/toolsmenu.jsx, online/src/worker/legacy/controllers/wrapper.js, online/src/worker/legacy/core.js
Controllers are in place, and the dialog with a generate function, a group
selection, and a nice Coxeter symbol control.
There are no quaternion controls or render choices, yet.
=> 4D Polytope generation for online classic

online/src/worker/legacy/controllers/editor.js, online/src/workerClient/controllers-solid.js
I removed some debugging logs about camera and lighting, about preference properties
falling through the EditorController, and about the PLANES_DEFINED and
DESIGN_XML_PARSED messages not yet handled by viewer/solid.
=> Cleaning up noise on console

core/src/main/java/com/vzome/core/edits/SelectCoplanar.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
Just does what the PR title says. ;-)
=> Add new SelectCoplanar command

online/src/app/classic/menus/editmenu.jsx
Also added new "Select Coplanar".
=> Restored complex selection commands to Online

online/src/worker/vzome-worker-static.js
clientEvents had a subtle side-effect, so scenes were reported for the trackball
model.
I've also disabled trackball loading when doing a preview.
=> Fixed defect causing overwrite of scenes

online/src/app/classic/components/length.jsx, online/src/worker/fields/golden.js, online/src/worker/fields/heptagon.js, online/src/worker/fields/root2.js, online/src/worker/fields/root3.js, online/src/worker/java/com/vzome/jsweet/JsAlgebraicField.java
I had to implement JsAlgebraicField.getIrrational(i,f) first.
=> Correct scale-by control in the length panel

online/src/app/classic/menus/filemenu.jsx, online/src/worker/vzome-worker-static.js
Import command only worked once.  The fix was to set "value" to null.
=> Fix for bug in import

.github/workflows/build-linux.yml, .github/workflows/desktop.yml, .github/workflows/jekyll-to-dreamhost.yml, .github/workflows/jsweet.yml, .github/workflows/online.yml, .github/workflows/test-and-regression.yml, desktop/build.gradle
Also clean up some Windows git actions
=> Upgrade git actions to avoid deprecation warnings

online/src/app/classic/menus/filemenu.jsx, online/src/viewer/react/index.jsx, online/src/viewer/solid/export.jsx, online/src/workerClient/files.js, online/src/workerClient/index.js, online/src/workerClient/serializer.js
Save and saveAs are working fine, including use of the handle after a saveAs
or an open.
=> Open and Save using File System API

online/src/app/classic/classic.jsx, online/src/app/classic/components/alert.jsx, online/src/worker/vzome-worker-static.js
I switched from Kobalte to SUID.  Styling could be better, but it works.
I also started catching the empty file error that I hit with Dropbox for
files not downloaded.
=> Fixed alert for classic

core/src/main/java/com/vzome/xml/DomUtils.java, online/public/classic/classic.css, online/public/classic/rotate.png, online/public/classic/rotate.svg, online/src/app/classic/components/camera.jsx, online/src/app/classic/components/editor.jsx, online/src/app/classic/menus/contextmenu.jsx, online/src/app/classic/tools/dummy.jsx, online/src/app/classic/tools/selection.jsx, online/src/app/framework/menus.jsx, online/src/viewer/solid/geometry.jsx, online/src/viewer/solid/ltcanvas.jsx, online/src/viewer/solid/trackballcontrols.jsx
The JSX and CSS is done, working great.  Only "lookAtOrigin" and "lookAtThis" are
connected.
I have separated the camera trackball as a third mouse mode, so that there
is no conflict on right-click.
I have it working for picking scene objects!
I am also using the "rotate" cursor for the camera trackball view, by virtue of a
DummyTool for the Camera view.
Camera near & far still need to be controlled.
=> Context menu

online/src/app/classic/menus/contextmenu.jsx, online/src/viewer/solid/geometry.jsx, online/src/viewer/solid/ltcanvas.jsx, online/src/viewer/solid/perspectivecamera.jsx, online/src/viewer/solid/trackballcontrols.jsx, online/src/workerClient/controllers-solid.js
also a bug fix for updating the camera after file open (in non-camera mode)
=> more context menu items

online/src/app/buildplane/buildplane.jsx, online/src/app/buildplane/index.jsx, online/src/app/buildplane/planes.js
I fixed some defects:
1. The initial build plane was facing sideways
2. The strut previews were off in some cases
3. The title and about were wrong
I made the preview state have an explicit `forBall` boolean, and rendered the preview
with or without rotation based on that.
I also wrote a better about dialog.
=> Buildplane improvements

online/src/app/buildplane/planes.js, online/src/viewer/solid/fullscreen.jsx, online/src/viewer/solid/iconbutton.jsx, online/src/viewer/solid/index.jsx, online/src/viewer/solid/undoredo.jsx, online/src/viewer/solid/urlviewer.css.js
I added the IconButton component to the viewer, in the process... it is used for undo/redo
and expand/collapse view buttons.
I also restored the "lost center" code in the reducer, so undo is safe.
=> Restored undo/redo capability to buildplane

online/package.json, online/yarn.lock
Now the buffer is added, and the result is perfect.
=> Incorporate GLTFExporter fix

.vscode/launch.json, online/public/59icosahedra/index.html, online/public/models/pieces-aceg.vZome, online/public/models/pieces-all.vZome, online/public/models/pieces-bdfh.vZome, online/scripts/esbuild-config.mjs, online/src/app/59icosahedra/index.jsx, online/src/app/59icosahedra/selector.jsx, online/src/app/classic/components/camera.jsx, online/src/viewer/solid/geometry.jsx, online/src/workerClient/context.jsx
STATUS: three models showing with the right layout, and the two control models have locked cameras
with no pan or zoom.  Selector models are ready with complementary outlines in gray struts,
with cells defined as groups for selection.
The main model is ready as a preview, with the stellation diagram showing
TASKS:
- drive main model from selectors
=> WIP 59 Icosahedra app

desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java
The swatches are not lost during a vZome session.
=> Desktop color chooser with memory

online/src/app/59icosahedra/index.jsx, online/src/app/59icosahedra/selector.jsx, online/src/app/classic/components/appbar.jsx, online/src/app/classic/dialogs/about.jsx
I also rearranged the main text, the about text, and fixed the titles.
=> Fixed background click for 59icosahedra

core/src/main/java/com/vzome/core/viewing/Camera.java
I had added some getters without `@JsonIgnore` annotations.
=> Fixed camera JSON serialization bug

online/src/app/59icosahedra/index.jsx, online/src/worker/vzome-worker-static.js
I also corrected the main scene background color
=> Added switch for cutaway view

online/public/browser/index.html, online/public/buildplane/buildplane-app.png, online/public/buildplane/index.html, online/public/classic/classic-app.png, online/public/classic/index.html
This will make sharing better for classic, buildplane, and browser.
=> Added card metadata to three apps

desktop/src/main/java/org/vorthmann/zome/ui/ShareDialog.java
I also added the ability to customize the branch name as `githubBranchName`, and
added error and warning logging.
=> Removed force=true from EGit push

core/src/main/java/com/vzome/core/exporters/ShapesJsonExporter.java
David Hall tracked this down and recommended this fix... works great.
=> Corrected the shapes-json export issue

core/src/main/java/com/vzome/core/construction/PerspectiveProjection.java, core/src/main/java/com/vzome/core/construction/TransformedPoint.java, core/src/main/java/com/vzome/core/construction/TransformedSegment.java, core/src/main/java/com/vzome/core/kinds/DefaultFieldApplication.java, core/src/main/java/com/vzome/core/kinds/IcosahedralSymmetryPerspective.java, core/src/main/java/com/vzome/core/kinds/OctahedralSymmetryPerspective.java, core/src/main/java/com/vzome/core/tools/PerspectiveProjectionTool.java, core/src/main/java/com/vzome/core/tools/PerspectiveProjectionToolFactory.java, core/src/test/java/com/vzome/core/kinds/FieldApplicationTest.java, desktop/src/main/resources/icons/tools/newTool/perspective.png, desktop/src/main/resources/icons/tools/small/perspective.png
Everything appears to be working.  I had to add some guards against
pathological situations for `TransformedPoint` and `TransformedSegment`,
now that the transformation has singularities.
=> Adding perspective projection tool

cicd/install-vzome-online.bash
We have to marshall static resources from the main app to the new inspector app.
=> Updated local copy of online installer script

desktop/src/main/java/com/vzome/desktop/awt/ApplicationController.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java, desktop/src/main/java/org/vorthmann/zome/ui/LessonPanel.java, desktop/src/main/java/org/vorthmann/zome/ui/PagelistPanel.java
I made the design/scenes toggle UI a little clearer, and changed the labeling of everything.
I also removed the "as.template" behavior from `openURL`, so now scenes are loaded.
=> Article mode is now Scenes mode

.gitignore, online/public/test/index.html, online/src/wc/vzome-viewer.js, online/src/worker/vzome-worker-static.js
fixing race condition for slow network, and wrong showScenes contract for worker
=> fix two bugs

online/public/59icosahedra/responsive.css, online/public/App.css
This is working for most text in all apps, but not everywhere.
=> Made text non-selectable

online/src/wc/vzome-viewer.js
Since `attributeChangedCallback()` can happen before `connectedCallback()`,
I added a guard to wait until the dynamic module has been loaded.
=> Fixed race condition in web component

online/src/wc/vzome-viewer.js
I added `#updateCalled`.  Now, module load will trigger the worker only if
`#reactive` or if `#updateCalled`.
=> Viewer update API improved again

core/src/main/java/com/vzome/core/editor/api/Shapes.java, core/src/main/java/com/vzome/core/exporters/DaeExporter.java, core/src/main/java/com/vzome/core/model/Panel.java, core/src/main/java/com/vzome/core/model/PanelImpl.java, core/src/main/java/com/vzome/core/render/JsonMapper.java, core/src/main/java/com/vzome/core/render/RenderedManifestation.java, core/src/main/java/com/vzome/core/render/ShapeAndInstances.java, core/src/main/java/com/vzome/core/viewing/AbstractShapes.java, online/src/worker/java/com/vzome/jsweet/JsPanel.java
The basic idea is working, although panel quadrea is not being computed.
All shape-rendering exporters (POV, DAE, VRML, .shapes.json) have been
tested.  VRML seems right, but `vrml-viewer` doesn't do PROTO.
=> Reusing panel shapes

online/src/app/59icosahedra/selectors.jsx, online/src/app/classic/classic.jsx, online/src/app/classic/components/camera.jsx, online/src/app/classic/components/editor.jsx, online/src/app/classic/components/strutbuilder.jsx, online/src/app/classic/components/toolbars.jsx, online/src/app/classic/context/symmetry.jsx, online/src/app/classic/index.jsx, online/src/app/classic/menus/systemmenu.jsx, online/src/app/classic/menus/toolsmenu.jsx, online/src/app/classic/tools/snapcamera.jsx, online/src/app/classic/tools/trackball.jsx, online/src/viewer/context/editor.jsx, online/src/viewer/context/interaction.jsx, online/src/viewer/ltcanvas.jsx, online/src/viewer/trackballcontrols.jsx, online/src/worker/legacy/controllers/index.js, online/src/worker/legacy/controllers/wrapper.js, online/src/worker/vzome-worker-static.js
I'm not happy with the high traffic to the worker, lots of useless snap events
due to the poor event API from `TrackballControls` in three.js, but it is
working fine for the user.
=> Added snap behavior

docs/web-component.md, online/src/worker/vzome-worker-static.js
Preview polygons value was not being saved and sent with each scene.
=> Fixed a bug for preview scenes

desktop/src/main/java/org/vorthmann/zome/ui/ShareDialog.java
If the preference is set, it will share to that org, otherwise to the username.
=> GitHub sharing now supports githubOrgName

core/src/main/java/com/vzome/core/editor/LessonModel.java, desktop/src/main/java/com/vzome/desktop/awt/LessonController.java, desktop/src/main/java/org/vorthmann/zome/ui/PagelistPanel.java
Also, I added "save current view to ALL" as a contextual command for any
scene.
=> Added option for adding to the start of the scenes list

desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java
This is not pretty, since it requires the whole app startup, but it is at least
automatable.
```
vZome7.1 myDesign.vZome -imageFormat png
```
=> Added ability to automate image capture

desktop/src/main/java/com/vzome/desktop/awt/DocumentController.java, desktop/src/main/java/com/vzome/desktop/controller/GitHubApi.java, desktop/src/main/java/com/vzome/desktop/controller/ShareController.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java, desktop/src/main/java/org/vorthmann/zome/ui/ShareDialog.java
=> Refactored ShareController out of ShareDialog

online/src/viewer/index.jsx
I tried the solid-primitive on another branch, but it does not work.  The only
trick here was to listen to the fullscreenchange event, and only use my signal
as derived state.
=> Full viewport mode is now full screen mode

core/src/main/java/com/vzome/core/exporters/GitHubShare.java, desktop/src/main/java/org/vorthmann/zome/ui/ShareDialog.java, docs/web-component.md
I also updated the web component documentation.
=> Added new "indexed (load-camera)" mode for sharing

desktop/src/main/java/org/vorthmann/zome/render/jogl/JoglRenderingViewer.java, desktop/src/main/java/org/vorthmann/zome/render/jogl/NearestPicker.java
The data flow for the Ray in JRV.mapWinToRay() was wrong.
=> Fixed picking defect

online/src/app/classic/components/camera.jsx, online/src/app/classic/index.jsx, online/src/app/classic/menus/filemenu.jsx, online/src/viewer/context/export.jsx, online/src/viewer/export.jsx, online/src/viewer/geometry.jsx, online/src/viewer/index.jsx, online/src/viewer/util/files.js
I also created `context/export.jsx` to support this, and moved the
GltfExportContext there.
=> Implemented image capture in classic

desktop/src/main/java/com/vzome/desktop/controller/ShareController.java
The repo list was not being filtered correctly.  I'm also logging a bit better
now.
=> Fixed GitHub sharing defect

online/src/viewer/cameramode.jsx, online/src/viewer/urlviewer.css.js
The corner icon buttons are now visible against any background color, and the
perspective toggle has a consistent styling.
=> Viewer controls style improvements

online/src/app/classic/components/toolbars.jsx, online/src/app/classic/dialogs/sharing.jsx, online/src/app/classic/dialogs/webloader.jsx, online/src/app/classic/menus/filemenu.jsx
This includes the GitHub sharing dialog.
=> Fixed keyboard events in all necessary dialogs

online/package.json, online/public/classic/classic.css, online/src/app/browser/users.jsx, online/src/app/classic/index.jsx, online/src/app/classic/menus/contextmenu.jsx, online/src/app/classic/menus/filemenu.jsx, online/src/app/classic/menus/help.jsx, online/src/app/framework/menus.jsx, online/src/app/framework/tabs.jsx, online/src/viewer/cameramode.jsx, online/src/viewer/context/editor.jsx, online/src/viewer/export.jsx, online/src/viewer/iconbutton.jsx, online/src/viewer/scenes.jsx, online/src/viewer/spinner.jsx, online/yarn.lock
This replaces the individual DropdownMenus, and works nicely!
I adopted Kobalte 0.13.3 to achieve this, and that required a number of simple
changes to imports, and removing `.Root` everywhere.
=> Added Kobalte Menubar

core/src/main/java/com/vzome/core/editor/Application.java, core/src/main/java/com/vzome/core/render/JsonMapper.java, desktop/src/main/java/com/vzome/desktop/awt/ApplicationController.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
Change "New Model" to "New Design" to match online classic menu.
Add notes about enabling menu items for other fields.
=> Enable snubCube and snubDodec fields for all users

online/build.gradle, online/src/worker/legacy/controllers/editor.js, online/src/worker/legacy/controllers/index.js, online/src/worker/legacy/core.js, online/src/worker/legacy/serializer.js, online/src/worker/vzome-worker-static.js
The Snapshot edits are retained, and the scenes ("article pages" or "notes") also.
This will need review when scene *authoring* is enabled.
=> Scenes now preserved by vZome Online classic

.vscode/launch.json, online/public/test/index.html, online/src/app/59icosahedra/state.jsx, online/src/app/browser/browser.jsx, online/src/app/browser/index.jsx, online/src/app/buildplane/index.jsx, online/src/app/classic/index.jsx, online/src/app/index.jsx, online/src/viewer/context/viewer.jsx, online/src/viewer/context/worker.jsx, online/src/viewer/index.jsx, online/src/wc/zometool.jsx, online/src/worker/vzome-worker-static.js
=> wait for worker

online/public/classic/classic.css, online/src/app/classic/classic.jsx, online/src/app/classic/context/commands.jsx, online/src/app/classic/dialogs/scenes.jsx, online/src/app/classic/dialogs/svgpreview.jsx, online/src/app/framework/context/editor.jsx, online/src/viewer/context/scene.jsx, online/src/viewer/context/worker.jsx, online/src/viewer/scenecanvas.jsx, online/src/viewer/util/actions.js, online/src/worker/vzome-worker-static.js
A read-only dialog showing all scenes.
I have created `SceneProvider` as subset of `ViewerProvider`.  It uses a new
mechanism, `WorkerContext.postRequest`.
I also changed `SceneCanvas` to use context when the `scene` property is
missing.
=> Scenes dialog for classic

core/src/main/java/com/vzome/core/editor/Snapshot.java, online/public/classic/classic.css, online/src/app/classic/classic.jsx, online/src/app/classic/components/scenecontrols.jsx, online/src/app/classic/dialogs/scenes.jsx, online/src/app/framework/context/editor.jsx, online/src/viewer/context/viewer.jsx, online/src/worker/legacy/controllers/index.js, online/src/worker/vzome-worker-static.js
no title editing
no thumbnails
no reorder
no remove
=> minimal scene authoring

online/src/viewer/urlviewer.css.js, online/src/wc/zometool.css.js, online/src/wc/zometool.jsx
- CSS for SVG icons to work on Safari
- improved CSS styling for zometool-instructions
- added step index display to zometool-instructions
- fixed "extra scene" defect for zometool-instructions
=> Bug fixes and enhancements

online/src/app/classic/dialogs/sharing.jsx, online/src/app/framework/context/editor.jsx
I also fixed the "BOM_CHANGED" warning.
=> Fixing GitHub "none" sharing style for online

core/src/main/resources/com/vzome/core/editor/defaultPrefs.properties, core/src/main/resources/com/vzome/core/editor/test-colors.html
Paul and I had a Zoom, going over `test-colors.html` with browser CSS debugger to
fine tune the 10 standard colors.
=> New standard Zometool colors

core/src/main/java/com/vzome/core/exporters/GitHubShare.java, core/src/main/resources/com/vzome/core/editor/defaultPrefs.properties, core/src/main/resources/com/vzome/core/exporters/github/indexTemplate.md, core/src/main/resources/com/vzome/core/exporters/github/instructionsTemplate.md, core/src/main/resources/com/vzome/core/exporters/github/postTemplate.md, core/src/main/resources/com/vzome/core/exporters/github/readmeTemplate.md, core/src/main/resources/com/vzome/core/exporters/github/viewerTemplate.md, desktop/src/main/java/org/vorthmann/zome/ui/ShareDialog.java, online/src/app/classic/dialogs/sharing.jsx
=> Added "Zometool Instructions" option for GitHub sharing

.vscode/launch.json, online/package.json, online/serve/app/classic/index.html, online/serve/app/index.html, online/serve/app/kobalte.css, online/serve/app/test/index.html, online/src/app/classic/components/camera.jsx, online/src/app/classic/components/zoomslider.jsx, online/src/app/index.jsx, online/src/viewer/context/camera.jsx
The slider is visible, and connected to state, working fine.  I had to add a
`setDistance` function to the camera context;
Styling is OK, but the whole app could use a design review.
=> Added zoom slider to classic

online/src/app/classic/components/length.jsx, online/src/app/classic/components/toolbars.jsx, online/src/app/classic/context/commands.jsx, online/src/app/framework/menus.jsx
I also corrected the long-standing "length.undefined" error.
=> Fixed missing tools and Windows key equivalents

cicd/jsweet-legacy-code.bash, online/README.md
I also removed the `--info` flag cluttering up the JSweet build.
=> Corrections to the README for online

core/src/main/java/com/vzome/core/construction/LineReflection.java, core/src/main/java/com/vzome/core/kinds/DefaultFieldApplication.java, core/src/main/java/com/vzome/core/kinds/HeptagonFieldApplication.java, core/src/main/java/com/vzome/core/kinds/IcosahedralSymmetryPerspective.java, core/src/main/java/com/vzome/core/kinds/OctahedralSymmetryPerspective.java, core/src/main/java/com/vzome/core/kinds/PolygonFieldApplication.java, core/src/main/java/com/vzome/core/kinds/RootThreeFieldApplication.java, core/src/main/java/com/vzome/core/kinds/RootTwoFieldApplication.java, core/src/main/java/com/vzome/core/tools/LineReflectionTool.java, core/src/main/java/com/vzome/core/tools/LineReflectionToolFactory.java, core/src/main/java/com/vzome/fields/sqrtphi/SqrtPhiFieldApplication.java, core/src/regression/files/2024/07-Jul/22-David-LineReflection/LineReflectionToolIcon.vZome, core/src/regression/files/sniff-test.vZome-files, core/src/test/java/com/vzome/core/kinds/FieldApplicationTest.java, desktop/src/main/resources/icons/tools/line reflection.png, desktop/src/main/resources/icons/tools/newTool/line reflection.png, desktop/src/main/resources/icons/tools/small/line reflection.png
Includes a regression file which is also the basis for the tool icons.
Seems to work fine with localhost online as well.
=> Add LineReflectionTool

online/serve/app/test/cases/zometool-model/index.html, online/src/wc/zometool/products-list.jsx, online/src/wc/zometool/zometool.css.js
A product with no URL is ignored.
=> Adjustments to zometool products list

online/serve/app/test/cases/zometool-model/index.html, online/serve/app/test/cases/zometool-model/styles.css
Changed to a model with correct colors, and adopted standard CSS from
the Zometool site.
=> Zometool model page updates

online/serve/app/test/cases/github-share-online/index.html, online/serve/app/test/cases/github-share/index.html, online/serve/app/test/gltf.html, online/src/viewer/context/camera.jsx
I also fixed a timing defect so that the initial tween always runs, and made some
cosmetic changes to test pages.
=> Set the tween default to 500ms

online/src/app/classic/menus/filemenu.jsx, online/src/worker/legacy/dom.js
1. GitHub sharing title derived from Dropbox correctly
2. `JavaDomElement` implements `setTextContent`
=> Two defect fixes

online/yarn.lock
This caused an immediate runtime error in online, thrown from within
`TrackballControls.js` when it tried to access the DOM document.
=> Somehow yarn.lock got bad versions

cicd/jsweet-legacy-code.bash, core/src/main/java/com/vzome/api/Exporter.java, core/src/main/java/com/vzome/core/exporters/DocumentExporter.java, core/src/main/java/com/vzome/core/exporters/DocumentExporterIntf.java, core/src/main/java/com/vzome/core/exporters/PartGeometryExporter.java, core/src/main/java/com/vzome/core/exporters/ShapesJsonExporter.java, desktop/src/main/java/com/vzome/desktop/awt/DocumentController.java, online/src/worker/legacy/core-java.js, online/src/worker/legacy/ts/com/vzome/core/editor/SymmetrySystem.ts, online/src/worker/legacy/ts/com/vzome/core/edits/ReplaceWithShape.ts, online/src/worker/legacy/ts/com/vzome/core/exporters/DocumentExporter.ts, online/src/worker/legacy/ts/com/vzome/core/exporters/DocumentExporterIntf.ts, online/src/worker/legacy/ts/com/vzome/core/exporters/OpenScadExporter.ts, online/src/worker/legacy/ts/com/vzome/core/exporters/POVRayExporter.ts, online/src/worker/legacy/ts/com/vzome/core/exporters/PartGeometryExporter.ts, online/src/worker/legacy/ts/com/vzome/core/render/RenderedManifestation.ts, online/src/worker/legacy/ts/com/vzome/core/render/RenderedModel.ts, online/src/worker/legacy/ts/com/vzome/core/viewing/ExportedVEFShapes.ts, online/src/worker/legacy/ts/com/vzome/core/viewing/ExportedVEFStrutGeometry.ts, online/src/worker/legacy/ts/core-java.ts, online/src/worker/legacy/ts/java/util/UUID.ts
The defect was introduced in a142589179b2a9a3b6434b4305c54d68d1444d0f
I have regenerated the Typescript (loose and bundled) and Javascript from the core Java.
=> Fixing the empty preview JSON bug

online/src/app/framework/context/editor.jsx
The `controllerAction()` is now guarded by `isWorkerReady()` automatically
=> Fixed early controller actions

online/src/app/classic/menus/filemenu.jsx, online/src/app/framework/context/editor.jsx, online/src/app/index.jsx, online/src/worker/legacy/controllers/index.js, online/src/worker/legacy/core.js
Not sure about 953, but hopeful.  Sure about 952 and 954.
=> Fixes for 3 online bugs

online/src/app/classic/dialogs/scenes.jsx, online/src/worker/vzome-worker-static.js
I'd like better icons, but the behavior is working perfectly.
Still no Tooltip from SUID!
=> Adding basic camera transfers to scenes dialog in online

online/src/viewer/context/camera.jsx, online/src/viewer/context/scene.jsx, online/src/viewer/context/viewer.jsx
Parts still just appear or disappear instantaneously... no fade-in or fade-out yet.
=> Scene animation now does camera first then parts

.github/workflows/desktop.yml
The JSON file for each artifact is built only after the successful upload of the artifact.
=> Added buildNumber capture to GitHub Action for desktop

.github/workflows/desktop.yml
The output log has more information than last time I looked (2 years ago?), so I
think I have a solution.
=> Trying fix for Windows SSH failure

online/serve/app/classic/classic.css, online/src/app/classic/components/scenecontrols.jsx, online/src/app/classic/dialogs/scenes.jsx, online/src/app/framework/context/editor.jsx, online/src/viewer/context/scene.jsx, online/src/worker/vzome-worker-static.js
Everything's fine except... I'm not happy that scene context depends on editor
context for reload.  SceneContext is meant to replace similar functionality in
ViewerContext, so it can't depend on EditorContext.
=> Button for remove scene

desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java, desktop/src/main/java/org/vorthmann/zome/ui/ModelPanel.java
TODO: online menus should behave similarly
=> Only show Tetrahedral Symmetry menu item for fields with icosa symmetry

.vscode/launch.json
I don't know how this works... does it figure out how to do the build?
=> Adding launch config for desktop vZome

online/src/app/browser/browser.jsx, online/src/app/browser/gists.js, online/src/app/browser/github.js
I've incorporated the code from `ggorlen/gist-list`.
The feature is working perfectly, including all the top buttons, which needed
some changes for gists.
=> List GitHub gists in the online browser

desktop/src/main/java/com/vzome/desktop/awt/DocumentController.java, desktop/src/main/java/com/vzome/desktop/controller/ShareController.java, desktop/src/main/java/org/vorthmann/zome/ui/ShareDialog.java
I also improved the failure messages for offline sharing, and improved the dialog
layout.
=> Desktop: disable scene sharing when there are none

online/serve/app/test/cases/field-api/index.html, online/serve/app/test/index.html, online/src/worker/legacy/controllers/editor.js, online/src/worker/legacy/controllers/index.js, online/src/worker/legacy/core.js, online/src/worker/legacy/dynamic.js, online/src/worker/vzome-worker-static.js
... in a worker.
This seems to be working, at the cost of
an API change for the `vzome-legacy.js` module.
=> Fixing Safari problem with top-level await in a dynamic import

online/serve/app/test/cases/scene-descriptions/index.html, online/serve/app/test/index.html, online/src/app/classic/dialogs/scenes.jsx, online/src/app/classic/menus/contextmenu.jsx, online/src/wc/vzome-viewer.js, online/src/worker/legacy/controllers/editor.js, online/src/worker/legacy/dom.js, online/src/worker/legacy/parser.js, online/src/worker/legacy/preview.js, online/src/worker/legacy/serializer.js, online/src/worker/vzome-worker-static.js
There is also a new event for the web component, with full scenes info.
I also implemented "undo including this" in online.
=> Online now preserving scene descriptions

desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java, docs/quick-start.md, online/src/app/classic/menus/help.jsx
I also updated links in the help menu, for both desktop and online.
=> Adding quick-start dodec to the quick-start docs page

docs/sharing.md
It did not mention `your-username-here` or the timezone config.
=> Fixed sharing doc

core/src/main/java/com/vzome/api/BulkConverter.java
Ahaaa Math requested a headless tool to generate "trishapes" exports for
vZome designs.
=> Added BulkConverter

cicd/jsweet-legacy-code.bash, cicd/online.bash, online/build.gradle
This now captures the Typescript automatically, both bundled and un-bundled.
=> Automated 2-phase JSweet

online/src/viewer/context/camera.jsx
Parts did not appear if animation was canceled.
=> Fixed issue with tween cancel

desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java
Introduced in commit c7abccd7b8340b4e320a71215b359ae33bca8429
=> Fix macro replacement bug in execCommandLine

core/src/main/java/com/vzome/core/exporters/STEPExporter.java, desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
The output now seems correct, though I cannot judge the scale.
I have moved the exporter into the "export panels..." submenu.
=> Exporting only panels from STEP exporter

core/src/main/java/com/vzome/core/exporters/STEPExporter.java, online/build.gradle, online/src/app/classic/menus/filemenu.jsx, online/src/worker/legacy/core-java.js, online/src/worker/legacy/exporters.js, online/src/worker/legacy/ts/com/vzome/core/editor/SymmetrySystem.ts, online/src/worker/legacy/ts/com/vzome/core/edits/ReplaceWithShape.ts, online/src/worker/legacy/ts/com/vzome/core/exporters/STEPExporter.ts, online/src/worker/legacy/ts/com/vzome/core/render/RenderedModel.ts, online/src/worker/legacy/ts/core-java.ts
I had to add it to the JSweet step.
=> Adding STEP exporter to online vZome

.github/workflows/website.yml, docs/capture-vector-graphics.md, docs/index.md, docs/online.md
This commit should trigger a website build.
=> Updating some of the docs

online/serve/app/localfiles/index.html, online/serve/app/test/index.html, online/src/viewer/util/actions.js, online/src/wc/vzome-viewer.js, online/src/worker/vzome-worker-static.js
This is not terribly useful, since it has no means of opening a model in an editor.
It really needs to be incorporated into online vZome, but I'm not sure about the
user flows yet.
=> Adding file browser app

online/src/viewer/geometry.jsx, online/src/viewer/ltcanvas.jsx
This may fix the intermittent zero-length images during share to GitHub.
=> Adding GL preserveDrawingBuffer

online/serve/app/classic/classic.css, online/src/app/classic/context/commands.jsx, online/src/app/classic/dialogs/scenes.jsx, online/src/viewer/context/viewer.jsx
=> Scene titles and descriptions for online

online/serve/app/classic/classic.css, online/src/app/classic/context/commands.jsx, online/src/app/classic/dialogs/scenes.jsx
I also fixed "save" so it clears the "edited" signal.
=> Scene title editing

online/serve/app/test/cases/github-share/index.html, online/src/worker/legacy/preview.js
=> Fixed embedding for legacy preview
