vZome/vzome

core/src/main/java/com/vzome/core/editor/AxialStretchTool.java
core/src/main/java/com/vzome/core/editor/LinearMapTool.java
core/src/main/java/com/vzome/core/editor/RotationTool.java
core/src/main/java/com/vzome/core/editor/ScalingTool.java
core/src/main/java/com/vzome/core/editor/TranslationTool.java

Non-symmetry tools should use DELETE as their default input behavior.
The icon for axial symmetry is now fixed, also.

Fix tool UX defects

---

desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java

Can be used in vZomeCustomMenu.properties.  Format there is:
execCommandLine/<shell-command-line> = Your Menu String
Whitespace, ':', and '=' characters in <shell-command-line> must be escaped: '\:',
since the vZomeCustomMenu.properties file uses java.util.Properties.load() syntax.
The command line will be executed with the current working directory as the
directory containing the vZome save file.  The vZome save file name can be
substituted into the command line by using "{}" in <shell-command-line>.

Added execCommandLine action

---

desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java

When an exception occurred during document load, the application controller's document count was no longer correct, so closing the last document window did not call system.exit and the JVM was not terminated. This PR fixes that problem.

Correct document count after failing to load a document

---

core/src/main/java/com/vzome/core/editor/AxialStretchTool.java

This defect was left over from the FieldApplication refactoring.  The createToolInternal()
implementation was still expecting to parse the category out of the ID.  Since the factory
already knows the category, we should not need to parse the ID at all.

Fixed red/yellow stretch/squash tools

---

core/src/main/java/com/vzome/core/algebra/AlgebraicField.java
core/src/main/java/com/vzome/core/commands/CommandCentroid.java
core/src/main/java/com/vzome/core/commands/XmlSaveFormat.java
desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java

Unsupported Symmetries and Directions in vZome files threw NPEs. This simply replaces the NPEs with IllegalStateExceptions which provide more helpful debugging information. 
This was occurring on some sqrtPhi models that were developed with pre-released code having features (like icosahedral symmetry) that is not yet implemented in the current released version.

Replace two NPEs with more informative IllegalStateExceptions

---

core/src/main/java/com/vzome/core/editor/DocumentModel.java
core/src/main/java/com/vzome/core/editor/PolarZonohedron.java

Add a new polar zonohedron command only to core at this point. It can be manually added to the custom menu with the following line:
polarZonohedron=Construct Polar Zonohedron
Note that it accepts either of two input selections as described in the error message. One uses symmetry and the other is completely ad-hoc.

Add polar zonohedron command to core

---

desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java

This fix finally allows double clicking on a vZome file to open vZome in Windows as it should. Everything should still work as it has on the MAC, but please verify that it does. As noted in the comments, it's possible that we can use the new windows code on the MAC as well instead of resorting to nested try blocks. If that works, it will be cleaner, so please do so. Thanks.

Fix vZome file association on Windows

---

core/src/main/java/com/vzome/core/algebra/AlgebraicVectors.java
core/src/main/java/com/vzome/core/editor/ManifestationColorMappers.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java

Both of these new color mappings are helpful in determining strut and panel orientations. (e.g. when a meta-model panel might be flipped and need to be inverted or to see whether parallel strut vectors point the same direction or in opposite directions.

Add two new color mapping commands

---

desktop/src/main/java/org/vorthmann/zome/app/impl/ApplicationController.java
desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java

See the code comments for a description of the use case. Note that this commit incorporates the other open PR for the windows-file-uri repo, so that PR is unnecessary if this one is accepted.

Allows a "proxy" image file to be specified when opening a vZome file.

---

core/src/main/java/com/vzome/core/algebra/BigRational.java
core/src/test/java/com/vzome/core/algebra/BigRationalTest.java

* Added a test case to calculate harmonic means series. This is where the problem was originally discovered.

Improve accuracy of BigRational.evaluate() for very large fractions

---

core/src/main/java/com/vzome/core/exporters/StlExporter.java

The export values are now in inches, with no implicit scaling between
the model as seen in vZome and as exported.
Also removed any handling of balls and struts.

Fixed STL exporter to use actual size

---

core/src/main/java/com/vzome/core/editor/DocumentModel.java
core/src/main/java/com/vzome/core/editor/EditHistory.java
desktop/src/main/java/org/vorthmann/ui/Controller.java
desktop/src/main/java/org/vorthmann/ui/DefaultController.java
desktop/src/main/java/org/vorthmann/zome/app/impl/ApplicationController.java
desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java
desktop/src/main/java/org/vorthmann/zome/app/impl/UndoRedoController.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java

This refactoring establishes a pattern for further cleanup of DocumentController.
It eliminates one layer of “dispatch” code in DocumentModel, and moves
another layer from DocumentController to UndoRedoController.  Finally,
the latter can use a specific model, EditHistory.
I added EditHistory.Listener.publishChanges() to further clean up a little,
but I’m not sure if this is the right pattern for doing SelectionChanges
notifyListeners().

Extracted UndoRedoController

---

core/src/regression/java/com/vzome/experiments/GenerateLinearMaps.java

Allow the entire project to compile by replacing doc. undo() with doc. getHistoryModel() .undo() since doc.undo() method has been removed.

Fix compile error in GenerateLinearMaps

---

build.gradle
core/src/regression/java/com/vzome/experiments/GenerateLinearMaps.java
core/src/test/java/logging.properties
desktop/build.gradle

UTF-8 encoding is standard for Mac. It must be explicitly specified for Windows to properly show extended characters to stdout, stderr, log files and exported text files. Note that this PR also includes the undo-fix PR.

Specify UTF-8 encoding for Windows

---

core/src/main/java/com/vzome/core/commands/CommandImportVEFData.java
core/src/main/java/com/vzome/core/construction/VefToModel.java
core/src/main/java/com/vzome/core/math/VefParser.java

No functional change, just a little code cleanup.

Remove unused references to VefParser.usesActualScale()

---

desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java

Don't know how this little detail went un-noticed until now.

Show coordinates of strut end in properties dialog

---

core/src/main/java/com/vzome/core/editor/JoinSkewLines.java

The  JoinSkewLines command wouldn't load from a file because NAME should have been PascalCased instead of camelCased.

Fix bug reloading JoinSkewLines command from a file

---

desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java
desktop/src/main/java/org/vorthmann/zome/app/impl/Java2dSnapshotController.java

Background is on by default, and panel outlines are shown only
if they are on in the main view, so that the 2d export / rendering
is more WYSIWIG.

Improved defaults for 2d export

---

desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java

Using system look-and-feel.  Can be disabled with -Dvzome.disable.system.laf=true on the command line.

Look and feel

---

desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java

* Reflection was previously used to report the log file name.
* Not allowed in Java 9 and newer.

Remove Illegal reflective access warning in preparation for Java 11

---

desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java

Build 45 logs a null coreVersion at startup. Since desktop and core should have the same version, it is no longer necessary to log both. Commit 1b6e7ffebc17b490bff65b99d5782e48acf1b467 removed the initialization of the coreVersion property. This commit simply removes it from the log as well.

Remove logging of null core-version at startup

---

core/src/main/java/com/vzome/core/algebra/BigRational.java
core/src/main/java/com/vzome/core/algebra/Fields.java
core/src/test/java/com/vzome/core/algebra/AlgebraicFieldTest.java

The original GaussJordanReduction method only worked with square matrices. This was OK since it was only ever called by invert() which only uses square matrices. However, I found that I need to use GausJordanReduction on non-square matrices in my parameterizedField branch, so I an introducing these changes and test cases as a stand-alone commit to be merged into master ASAP.

Fix GaussJordanReduction to work with non-square matrices

---

desktop/src/main/java/com/vzome/desktop/controller/CameraController.java
desktop/src/main/java/org/vorthmann/zome/ui/CameraControlPanel.java

Initial state of the checkbox was out of sync.
The problem was that the CameraController needs a permanent "false"
value for the drawOutlines property, for rendering the trackball, but
needs to use the parent property to drive the checkbox.

Fixed the bug with the "outlines" checkbox

---

desktop/src/main/java/org/vorthmann/zome/app/impl/ApplicationController.java

In Windows, double clicking on an associated vZome file opens that file in vZome using the "file" protocol, rather than "http" as the MAC does.

Fix ClassCastException when opening vZome via Windows file association

---

desktop/src/main/java/org/vorthmann/zome/app/impl/UndoRedoController.java

With useBlocks=false, one can undo part of a begin/end block, which
breaks invariants.

Remove the undo/redo behavior change for developers

---

core/src/main/java/com/vzome/core/editor/Application.java
desktop/platform/mac/src/main/java/com/vzome/platform/mac/Adapter.java
desktop/src/main/java/org/vorthmann/j3d/Platform.java
desktop/src/main/java/org/vorthmann/zome/app/impl/ApplicationController.java
desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java

On Windows, drag-n-drop or double-click results in a file URI being
passed as a command-line argument.  To handle this, we were treating all
command-line path arguments as URLs, and the "openurl" action had code
to handle File URIs.
A better way is to treat paths we *know* are files as files, and use the
"open" action.  "openurl" is reserved for the menu command, and file URIs
are NOT supported there.
Unfortunately, the diffs in ApplicationUI are obscured by reformatting.
Note that we deal with Windows immediately on line 223.  Note also that
we no longer use "defaultAction"... instead we have the if stmt on line 286.

Command-line file arguments avoid openurl

---

core/src/main/java/com/vzome/core/editor/ToolsModel.java

Before we serialized tool labels, hiding, and behaviors, tools used the
construct-time defaults when loaded from a file.  Some recent change
broke this for such legacy tools, setting the inputBehaviors to null.

Fixed the defect in deserializing legacy tools

---

core/src/main/java/com/vzome/core/kinds/GoldenFieldApplication.java

The "cubic / octahedral symmetry" command in the icosa system was doing
icosa symmetry!

Corrected octasymm bug

---

core/src/main/java/com/vzome/core/edits/ManifestationColorMappers.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java

These color maps will set the color of automatic struts and panels to the same color as the nearest predefined (non-automatic) direction for the current symmetry. It's a convenient way to show what predefined direction is closest to a given automatic direction.  Earlier versions of vZome will treat unrecognized color maps as no-ops, so they can still open a model that uses this new color mapping.

Add 2 new "Nearest Predefined Orbit" Color Maps

---

core/src/main/java/com/vzome/core/model/Manifestation.java
core/src/main/java/com/vzome/core/model/RealizedModel.java
core/src/main/java/com/vzome/core/render/RenderedManifestation.java
core/src/main/java/com/vzome/core/render/RenderedModel.java

Default Manifestation color is still null.  If null, the current coloring rules apply, first
using the rendering style then the symmetry.  Coloring a Manifestation means that
the specific color will always apply.  Hide/show and delete+undo restore colors,
since the colors are stored in the Manifestations in the history.

Color now attached to Manifestation

---

core/src/main/java/com/vzome/core/edits/ManifestationColorMappers.java
core/src/main/java/com/vzome/core/model/Connector.java

Fix bug in CopyLastSelectedColor when last selected manifestation is a ball with a null color.

Set Connector color to WHITE instead of null

---

core/src/main/java/com/vzome/core/model/Manifestation.java

Problem is manifested by CopyLastSelectedColor when last selected object is a strut or panel with its default system color.

Fix null value of manifestation.color

---

server/src/main/java/com/vzome/server/ControllerWebSocket.java

Since commit 448caebba, the DocumentController is now providing a web
color string (with "#"), where it used to return null, apparently.

Fixed bug in backgroundColor for client-server

---

desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java

Logger's FileHandler was not being initialized if the log folder already existed. This resulted in no log files being generated. This was broke in commit d51257ec0369c74e631fd3c2ff133bbef75adcfc

Fix missing log files

---

core/src/main/java/com/vzome/core/editor/DocumentModel.java
core/src/main/java/com/vzome/core/render/RenderedModel.java
core/src/main/java/com/vzome/core/render/RenderingChanges.java
core/src/main/java/com/vzome/core/render/TransparentRendering.java
core/src/test/java/com/vzome/core/render/RenderedModelTest.java
desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java
desktop/src/main/java/org/vorthmann/zome/app/impl/PartsController.java
desktop/src/main/java/org/vorthmann/zome/app/impl/SymmetryController.java
desktop/src/main/java/org/vorthmann/zome/render/java3d/Java3dSceneGraph.java
desktop/src/test/java/org/vorthmann/zome/app/impl/LengthPanelControllersTest.java

Added RenderingChanges.shapesChanged().  It returns false when unsupported,
and none of the implementations support it yet.
Added RenderedModel.setShapes().  This calls RC.shapesChanged(), and if
it returns false, it falls back to doing setOrbitSource(), as if the
entire symmetry had been changed.  This is obviously overkill, but it has
been the implementation forever.  Now I have laid the groundwork to fix
that.

Support for smarter shape changes

---

desktop/src/main/java/org/vorthmann/zome/render/jogl/JoglRenderingViewer.java

Handling maxSize the same way we did for Java3d.
What we should probably do here is use this.aspectRatio when this.width
has been set, then we can pass in a very large maxSize and capture images
big enough for Neatoshop, etc.  Actually, for that purpose we would want
minSize.

Fixed image capture for article thumbnails

---

desktop/src/main/java/org/vorthmann/zome/render/jogl/JoglScene.java
desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java

I still get occasional ConcurrentModificationExceptions thrown which lock up the model rendering. What do you think of this solution? I think it's easier than synchronizing access to all of the related collections.
P.S. I also bumped the log file version number to 7.0.

Ignore ConcurrentModificationException in JoglScene.render()

---

core/src/main/java/com/vzome/core/kinds/GoldenFieldApplication.java
core/src/main/java/com/vzome/core/kinds/SnubDodecFieldApplication.java

The icosahedral symmetry tool factory was being replaced with an octahedral
symmetry tool factory from the base class.

Fixed symmetry bug introduced in last PR

---

core/src/main/java/com/vzome/opengl/OpenGlUtilities.java
core/src/main/java/com/vzome/opengl/OutlineRenderer.java
core/src/main/java/com/vzome/opengl/SolidRenderer.java

Avoid fatal exception when fog shader fails to compile because getFogFactor must specifically return floats rather than ints (e.g. 1.0 instead of just 1). Problem was in both SolidRenderer and OutlineRenderer. Problem was hardware specific, so error logging was also improved in case we need to identify similar openGL issues for other users.

Fix fog shader code to compile on David's ATI Radeon laptop

---

desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java
desktop/src/main/java/org/vorthmann/zome/ui/ControllerFileAction.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java

I'm now calling FileDialog.setFile() to prepare the file name with the
right extension.  If the file has been opened or saved, then the
"window.file" property should be non-null, and I'm using that to set up
the file name, stripping off the extension (presumably .vZome) and adding
the correct one.
Note that the whole business of "window.title", "window.file", and "name"
properties is pretty confusing, in addition to DocumentFrame.mFile state.
I should probably unify "window.file" and "name" properties.  Until this
commit, "window.file" was only set for opened files, not for saved ones.
Now it should be an invariant.

Better file name defaults in export/save dialogs

---

desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java

In DocumentMenuBar, we look up the *initial* symmetryController, and use
that for many of the items in the "Tools" menu.  This seems bizarre,
since of course it does not adapt to symmetry system changes!
Nonetheless, it may work for most of those commands, but it clearly fails
for ReplaceWithShape, since you can only get the shape for the default
symmetry system.
The fix was easy... use the DocumentController, and there dispatch to
the current symmetryController.
I do need to test some of the "oldTools" like axialsymm... there seems to
be a good chance that they also get stuck in the wrong system.  At the
very least, if they work correctly, it is only because we never even
retain the context from the symmetryController, instead reconstructing
the symmetry system deeper in core.

Fix for the wrong-symmetry bug for ReplaceWithShape

---

core/src/main/java/com/vzome/core/render/RenderedManifestation.java

The old logic of defaulting the color to white doesn't work now that the
Manifestation may set its color from the RM.  This means that the "color-
saving" logic later always saves white.
While I was fixing this, I added shape-specific colors, to be consistent
with strut coloring.

Fixed the bug making panels white on symmetry switch

---

core/src/main/java/com/vzome/fields/sqrtphi/SqrtPhiFieldApplication.java

* When invoked from the main menu, CommandSymmetry was using the wrong symmetry so it effectively generated the same result as CommandAxialSymmetry.
* This commit fixes the behavior when invoking the octasymm command from the main menu for new models. It works regardless of the current symmetry setting.
* There is no problem opening existing models that were created with this erroneous behavior because the original "symmetry.group" is read from the vZome file, not the corrected SymmetryPerspective.
* TODO: Note that the octasymm command is implemented by some SymmetryPerspectives but not others. For consistent behavior and a single code path, it should be implemented once in DefaultFieldApplication.getLegacyCommand() with rather than being duplicated in the getLegacyCommand() of …

Fix octasymm command when invoked from main menu for SqrtPhiField

---

core/src/main/java/com/vzome/core/commands/CommandPolygon.java

The purple-strut-model bug that triggered all my efforts at building a
debugger is now resolved.  It turns out that CommandPolygon was not using
the ordered-selection flag, amazingly.  This means that if you build a
panel, then undo just that command, and build the panel again (not redo!),
the second panel will be the reverse of the first.

Fixed the mysterious reversing panel

---

core/src/main/java/com/vzome/core/commands/CommandTransform.java
core/src/main/java/com/vzome/core/construction/MoveAndRotate.java
core/src/main/java/com/vzome/core/construction/Transformation.java
core/src/main/java/com/vzome/core/edits/AffineTransformAll.java
core/src/main/java/com/vzome/core/edits/DodecagonSymmetry.java
core/src/main/java/com/vzome/core/edits/FreeMove.java
core/src/main/java/com/vzome/core/edits/TransformSelection.java
core/src/main/java/com/vzome/core/tools/TransformationTool.java
desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java
desktop/src/main/java/org/vorthmann/zome/app/impl/PickingController.java
desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java
desktop/src/main/java/org/vorthmann/zome/ui/ModelPanel.java

This edit is needed for VR, where an object can be grabbed and moved to
a new location and orientation.
I also refactored a bit to create Transformation.transform(Construction),
which knows what to do with points, segments, and polygons.
Finally, I deferred the creation of the DapAdapter until we know we need
it.  It was failing to build in Eclipse, missing the DAP JAR for some
reason.

Added the FreeMove undoable edit

---

core/src/main/java/com/vzome/core/kinds/AbstractSymmetryPerspective.java
core/src/main/java/com/vzome/core/kinds/HeptagonFieldApplication.java
core/src/main/java/com/vzome/core/kinds/IcosahedralSymmetryPerspective.java
core/src/main/java/com/vzome/core/kinds/OctahedralSymmetryPerspective.java
core/src/main/java/com/vzome/core/kinds/RootThreeFieldApplication.java
core/src/main/java/com/vzome/core/kinds/RootTwoFieldApplication.java
core/src/main/java/com/vzome/core/kinds/SnubDodecFieldApplication.java
core/src/main/java/com/vzome/core/math/symmetry/AbstractSymmetry.java
core/src/main/java/com/vzome/core/math/symmetry/DodecagonalSymmetry.java
core/src/main/java/com/vzome/core/math/symmetry/IcosahedralSymmetry.java
core/src/main/java/com/vzome/core/math/symmetry/OctahedralSymmetry.java
core/src/main/java/com/vzome/core/math/symmetry/Symmetry.java
core/src/main/java/com/vzome/core/tools/SymmetryTool.java
core/src/main/java/com/vzome/fields/heptagon/HeptagonalAntiprismSymmetry.java
core/src/main/java/com/vzome/fields/heptagon/TriangularAntiprismSymmetry.java
core/src/main/java/com/vzome/fields/sqrtphi/PentagonalAntiprismSymmetry.java
core/src/main/java/com/vzome/fields/sqrtphi/SqrtPhiFieldApplication.java
core/src/test/java/com/vzome/core/apps/DumpBlueAngles.java
core/src/test/java/com/vzome/core/editor/RunZomodScript.java
core/src/test/java/com/vzome/core/generic/ComparableDirectionTest.java
core/src/test/java/com/vzome/core/math/symmetry/SymmetryTest.java
core/src/test/java/com/vzome/core/zomic/ZomicASTTest.java
core/src/test/java/com/vzome/core/zomic/program/PrintVisitor.java
core/src/test/java/com/vzome/fields/heptagon/HeptagonalAntiprismSymmetryTest.java

Minor cleanup of the Symmetry class, just for my own clarity. Comments in the commits should explain the changes. No functional changes.

Remove unused Symmetry.defaultStyle and make OctahedralSymmetry.frameColor protected

---

core/src/main/java/com/vzome/core/tools/MirrorTool.java

Tool was never fully implemented, but was shown on the toolbar. It threw an NPE when clicked.

Implement SqrtPhi built-in red mirror tool

---

core/src/main/java/com/vzome/core/algebra/AlgebraicVector.java
core/src/main/java/com/vzome/core/edits/LoadVEF.java
core/src/main/java/com/vzome/core/kinds/RootTwoFieldApplication.java
core/src/main/java/com/vzome/core/math/symmetry/AbstractSymmetry.java
core/src/main/java/com/vzome/core/math/symmetry/IcosahedralSymmetry.java
core/src/main/java/com/vzome/core/math/symmetry/OctahedralSymmetry.java
core/src/main/java/com/vzome/core/math/symmetry/Symmetry.java
core/src/main/java/com/vzome/fields/heptagon/HeptagonalAntiprismSymmetry.java
core/src/main/java/com/vzome/fields/sqrtphi/PentagonalAntiprismSymmetry.java
desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java

This command simply adds a triangle to the model at the 3 vectors returned by getOrbitTriangle().
No new command in core. Implemented in desktop app via LoadVEF. Invoked by custom menu entry.

Add new showOrbitTriangle diagnostic command to desktop app

---

core/src/main/java/com/vzome/core/algebra/AlgebraicField.java

This is necessary to avoid NPE in ParameterizedField c'tor.

Defer initialization of AlgebraicField.smallSeries until first use.

---

core/src/main/java/com/vzome/core/construction/PlaneProjection.java
core/src/regression/files/2020/04-Apr/19-David-FixProjectionToPlane/FixProjectionToPlane.vZome
core/src/regression/files/sniff-test.vZome-files

* Return an appropriate Construction when a Panel is projected down to a Segment or a Segment is projected down to a Point.
* This occurs when the projection vector is collinear with a strut or coplanar with a Panel.
* This was previously returning a degenerate Construction of the same general type as the one being projected which caused a subsequent BUG_ACCOMMODATION to be logged.
* Added a new model to the regression suite which specifically uses the RenderedManifestations generated by these conditions.

Fix BUG_ACCOMMODATION in PlaneProjection

---

core/src/main/java/com/vzome/core/commands/CommandImportVEFData.java
core/src/main/java/com/vzome/core/commands/CommandUniformH4Polytope.java

At some point, we must have changed the meaning of AV.toString().  The
defect occurred when saving a file that used one of these old commands.

Fix serialization problem for legacy quaternion commands

---

core/src/main/java/com/vzome/core/construction/Construction.java
core/src/main/java/com/vzome/core/editor/ApplyTool.java
core/src/main/java/com/vzome/core/editor/ChangeManifestations.java
core/src/main/java/com/vzome/core/model/Manifestation.java
core/src/main/java/com/vzome/core/tools/TransformationTool.java

It was easy enough to capture and transfer colors in ApplyTool and
TransformationTool.
The only glitch was that struts created by drag or join had no color, and
Manifestation.mRendered had been cleared by the time M.getColor()
was called.  Thus, the color setting in M.setRenderedObject().

Retaining colors during transformations

---

client/src/components/modelcanvas-three.js
desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java
desktop/src/main/java/org/vorthmann/zome/app/impl/JsonClientShim.java

I added a property for completely bypassing rendering sync in "finish.load",
called "headless.open", and I'm setting it in JsonClientShim.  This means
the lesson model is ignored.
This also avoids loading the classes that trigger "Graphics system is
initialized" from CheerpJ runtime.

Fixed NPE due to lesson model thumbnails

---

core/src/main/java/com/vzome/core/editor/DocumentModel.java
core/src/main/java/com/vzome/core/tools/TetrahedralToolFactory.java

Built-in tetrahedral symmetry was always handled because of the test for
"." in the name of a tool, in AbstractToolFactor.deserializeTool().
However, for custom tetrahedral tools, the names were not prefixed this
way, so there was nothing in the serialization to distinguish tetrahedral
from octahedral or from icosahedral... the edit is always just "SymmetryTool".
The other option to fix this would be to register the TetrahedralToolFactory
explicitly in FieldApplication.registerToolFactories(), which is only for
deserialization, but that feels like a more impactful change than this one.

Fixed defect in loading model using custom tetrahedral symmetry

---

build.gradle
core/build.gradle
desktop/build.gradle
desktop/platform/mac/build.gradle

Due to my upgraded Catalina OS, what used to be a warning about some
native window APIs on Mac OS X has turned into an exception (as they
promised in the warning).  JOGL has a fix, according to Sven G, so I've
tried to upgrade to 2.4.0, although it is not available from Maven yet.
I found the RC builds, and adjusted the "Ivy" repos to pick them up.
I got a runtime error because they do not contain all the native libs
like the "jogl-all-main.jar", etc. that get published to Maven Central.
I manually listed all the necessary natives (7 each for jogl-all and
gluegen-rt), and now the app runs with "gr desktop:run".
In addition, I controlled the jreHome for the createApp task to OpenJDK 8,
and now the packaged Mac app also runs!  (The last release, 7.0.22, had
started to crash on startup, …

Updating JOGL to 2.4.0 to fix the NSWindow exception

---

desktop/src/main/java/com/vzome/desktop/controller/CameraController.java

For 7.0.18, we changed where the Scene was created, so it is owned by
either the DocumentController or the CameraController.  However, we were
re-creating the scene in CameraController with every symmetry change, and
only the original was hooked up to the rendering.

Fixed trackball panel symmetry switch bug

---

core/src/main/java/com/vzome/core/editor/DocumentModel.java
core/src/main/java/com/vzome/core/editor/EditorModelImpl.java
core/src/regression/files/2020/11-Nov/21-Scott-regression/build-with-this-switch-symm.vZome
core/src/regression/files/2020/11-Nov/21-Scott-regression/heptagon-test.vZome
core/src/regression/files/sniff-test.vZome-files

John Hall tripped over this one, though I think I may have seen it before.
We have to store all symmetries, not just the current one, due to sequences like this:
1. drag an icosahedral olive strut
2. switch to octahedral symmetry
3. do "build with this" on the olive strut
4. drag out a strut
5. switch back to icosahedral symmetry
The end result is that the command in step 4 records the name of an automatic orbit.
That automatic orbit must be captured in the file.
I have therefore added an "OtherSymmetries" element to the top-level.  For
backward-compatibility, this supplements the existing "SymmetrySystem"
element, rather than replacing it, and does not duplicate that system in the XML.

Fixed automatic orbit bug

---

client/src/components/geometry.js

The memoized shapedInstances cache has to store the embedded position and
vectors for the instance.  Since opposite struts ([a,b] and [b,a]) both
have the same ID, we have to consistently use one or the other.
The selected state is NOT stored.  Probably the color should not be, either,
or should be overridden with instance color anyway.

Corrected the reverse cached strut shape defect

---

client/src/bundles/mesh.js

It was sensitive to the order of the vectors argument.  Now it first
finds the minimum vector, then determines whether to increment in the
positive or negative direction.

Fixed canonicalizeId bug for polygons

---

core/src/main/java/com/vzome/core/editor/CommandEdit.java

Certain commands are set up to work in parallel, on a collection of points
or segments.  CommandMidpoint is an example for segments.  These were
broken because JSweet cannot do Class.isAssignableFrom().  I've replaced
it with the only two cases that matter.

Fixed a bug in certain CommandEdit classes

---

core/build.gradle

These were excluded from JSweet before I added the Editor subinterfaces.

Restoring AdjustSelectionByOrbitLength, and others.

---

client/src/bundles/jsweet.js

The constructor is found by xmlToEditClass, but the signature is wrong,
so it fails.  The fix is to simply let 'CommandEdit' go to the else part,
by putting a special case in xmlToEditClass.

Fixed CommandEdit constructor bug

---

client/package-lock.json
client/package.json
client/src/App.css
client/src/App.js
client/src/Article.js
client/src/bundles/camera.js
client/src/bundles/designs.js
client/src/bundles/files.js
client/src/bundles/jsweet.js
client/src/components/about.js
client/src/components/appbar.js
client/src/components/designs.js
client/src/components/folder.js
client/src/components/modelcanvas-three.js
client/src/components/spinner.js
client/src/fields/golden.js
client/src/index.js

This mainly involves decoupling the ModelCanvas from a single, global
current design, allowing it to take a design ID as a prop.
In order to make this well-defined, I had to decouple design IDs from
user-visible design names.
Ideally, each ModelCanvas instance would useEffect() to trigger its own
model load.  However, that caused an infinite loop when I tried it.

Adding a multi-design article route

---

desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java

For a new document, the controller never got attached, so the button was
dead after being enabled.

Fixed a bug for the Share button

---

build-client.bash
client/package.json
client/public/natives/com/vzome/cheerpj/RemoteClientShim_native.js

The JSweet transpile must happen when the react-vzome component is built,
separately from building the app here.

Removed the CheerpJ and JSweet parts from build-client.bash

---

core/src/main/java/com/vzome/core/edits/ColorMappers.java
core/src/main/java/com/vzome/core/edits/ManifestationColorMappers.java
core/src/main/java/com/vzome/core/viewing/ExportedVEFStrutGeometry.java
react-library/src/jsweet/bundle.js

I removed cls.isAnonymousClass() from ColorMappers interface. This was
causing an error during load for the JSweet-transpiled module.
I also removed a silly idiom for getting a fully-qualified class name
for the ExportedVEFStrutGeometry LOGGER init.  JSweet cannot do
Error.getStackTrace().
This does NOT address Jackpike's problem with setting objects to a black
color.  I suspect that the color value is acting "falsy".

Corrected two exceptions in static initializers

---

online/src/components/debugger.jsx

Importantly, the selected edit is now clearly red.  This prepares for the
ability to "go to this command".

Styled the debugger tree view for more functional presentation

---

core/src/main/java/com/vzome/core/edits/SelectParallelStruts.java
core/src/main/java/com/vzome/core/math/Polyhedron.java
core/src/main/java/com/vzome/core/math/symmetry/Axis.java

Fix a bug in SelectParallelStruts and suppress one warning as described in the individual unrelated commits. This fix may or may not affect the ability to render any given model depending how that model uses the selected results of this command. The gradle regression command runs clean as do existing unit tests. I did not write a new unit test for this fix, but manually tested it in the model where I discovered it. This fix should probably be run against the full regression suite. Note that it only has the potential to affect models using the SelectParallelStruts command with antiprism symmety in heptagonal or sqrtPhi fields and ultimately may not even affect them in any actual existing models.

Fix a bug in SelectParallelStruts

---

react-library/src/components/geometry.jsx
react-library/src/core/legacyjava.js

Since orientation must be performed before embedding, the orientation
matrices won't necessarily be orthogonal, so they cannot be correctly
converted to quaternions.

Switched from quaternions to matrices

---

online/src/App.jsx
online/src/components/debugger.jsx

Now the debugger and the canvas both fill the vertical space, and only
the TreeView gets a scrollbar when needed.
See the comment in debugger.jsx for where I found the solution.

Finally found a CSS approach for the debugger

---

react-library/src/components/hooks.js
react-library/src/components/urlviewer.jsx

The embedding support created a regression, when there is no matrix yet
for the group for an instance.
The defect in hooks.js may not have been a regression; this is probably
still just a symptom of a deeper issue, when the instances array can
accumulate null entries.

Fixed a regression recently introduced.

---

core/src/main/java/com/vzome/core/edits/Parallelepiped.java

This removes six transpile errors for JSweet.

Removed cast functions from Parallelepiped.java

---

core/src/main/java/com/vzome/core/construction/ChangeOfBasis.java
core/src/main/java/com/vzome/core/tools/LinearMapTool.java

LinearMapTool did not do any bindParameters() validation of the selection,
just relying on countsAreValid().  I've added logic to verify that both bases
(or just the single one) are coincident on a single vertex.
Since legacy edits only require the first two struts of a basis to be coincident,
I didn't add any validation in checkSelection(), since that would break existing
models.
Still TODO: validation of linear independence of the first basis, when there are two.

Fixing NPE in LinearMapTool

---

core/build.gradle
core/src/main/java/com/vzome/core/construction/ConstructionChanges.java
core/src/main/java/com/vzome/core/editor/CommandEdit.java
core/src/main/java/com/vzome/core/editor/api/ManifestConstructions.java
core/src/main/java/com/vzome/core/model/ColoredMeshJson.java
core/src/main/java/com/vzome/core/model/SimpleMeshJson.java
core/src/test/java/com/vzome/core/construction/VefToModelTest.java
core/src/test/java/com/vzome/core/editor/ApplicationTest.java
core/src/test/java/com/vzome/core/math/quickhull/TestSimpleExample.java

This enabled me to decouple ManifestConstructions from the JSON importers,
so I could remove four classes from the JSweet transpile, and eliminate
52 errors.

Unified both JSON import event interfaces into ConstructionChanges

---

desktop/src/main/java/org/vorthmann/zome/ui/ShareDialog.java
desktop/src/main/java/org/vorthmann/zome/ui/SymmetryToolbarsPanel.java
desktop/src/main/resources/org/vorthmann/zome/ui/githubReadmeBoilerplate.md

Nan discovered that embed.py worked fine with the raw content URLs, since
the PNG file still gets served with the correct MIME type.
I have therefore simplified everything, notably the generated README, to
remove the requirement for GitHub Pages at all.

No longer using GitHub Pages

---

desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java

Offending typo was export.vefg = Export vZome VEF

Fix: Typo in custom menu throws NPE.

---

desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java

Command "show.vZome-xml" is only to be invoked from custom menu.

Add command to print vZome XML to stdout without saving file.

---

core/src/main/java/com/vzome/core/kinds/SnubCubeFieldApplication.java
core/src/main/java/com/vzome/core/viewing/AbstractShapes.java
core/src/main/java/com/vzome/core/viewing/ExportedVEFShapes.java

Skip the unnecessary overhead of trying to load VEF and retry with fallback for automatic directions. Go straight to default struts since we know VEF or other fallbacks won't render auto struts. This should speed up the rendering of automatic struts, even if only a little bit.
Also added logging for missing VEF resources in ExportedVEFShapes to help track down why balls are not being loaded by the SnubCubeField in the gradle builds but they are in the Eclipse builds.
Eventually, we could make a test case to use this logging to track down missing strut geometries.

Optimize VEF strut geometry for automatic directions

---

core/src/main/java/com/vzome/core/algebra/EdPeggField.java
core/src/main/java/com/vzome/core/algebra/ParameterizedField.java
core/src/main/java/com/vzome/core/algebra/PlasticNumberField.java
core/src/main/java/com/vzome/core/algebra/PlasticPhiField.java
core/src/main/java/com/vzome/core/algebra/PolygonField.java
core/src/main/java/com/vzome/core/algebra/SnubCubeField.java
core/src/main/java/com/vzome/core/algebra/SuperGoldenField.java
core/src/main/java/com/vzome/fields/sqrtphi/SqrtPhiField.java
core/src/test/java/com/vzome/core/algebra/ParameterizedFieldTest.java
core/src/test/java/com/vzome/core/algebra/ParameterizedFields.java

Remove the unnecessary 'operand' member variable.
Move call to initialize() out of the base class.
Each derived class now calls initialize() in their c'tor after calling the base class c'tor.
Remove validate() from base class and only use it in PolygonField which actually has something to validate.

Remove type parameter from ParameterizedField

---

core/src/main/java/com/vzome/core/exporters/Exporter3d.java
core/src/main/java/com/vzome/core/exporters/ShapesJsonExporter.java
desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java
desktop/src/main/java/org/vorthmann/zome/ui/ShareDialog.java

This will allow vZome Online (or even other tools) to do a "3d preview",
or even just a read-only view, without any need to load or execute the
legacy vZome code.  This immediately sidesteps all issues relating to
interpretation errors in the transpiled code, until full editing is
available.
I've also updated the Shapes JSON exporter to include camera and lighting.

Saving shapes.json as part of GitHub shares

---

core/src/main/java/com/vzome/core/algebra/AlgebraicMatrix.java
core/src/main/java/com/vzome/core/editor/api/OrbitSource.java
core/src/main/java/com/vzome/core/exporters/ShapesJsonExporter.java
core/src/main/java/com/vzome/core/render/JsonMapper.java
core/src/main/java/com/vzome/core/viewing/Camera.java
core/src/main/java/com/vzome/unity/Renderer.java
desktop/src/main/java/com/vzome/desktop/controller/JsonClientRendering.java
online/src/App.jsx
online/src/bundles/camera.js
online/src/bundles/designs.js
online/src/components/designeditor.jsx
react-library/src/components/geometry.jsx
react-library/src/components/hooks.js
react-library/src/components/urlviewer.jsx
react-library/src/core/legacyjava.js

I can successfully render a .shapes.json file that is found next to a
.vZome file.
Camera and lighting details are carried over successfully, though Online
does not yet have a perspective | orthogonal switch.
Older shares (with no preview .shapes.json) still render successfully.
Also, legacy vZome files now render with their original background color.

Rendering shapes preview when available

---

core/src/main/java/com/vzome/core/algebra/AlgebraicField.java
core/src/main/java/com/vzome/core/algebra/HeptagonField.java
core/src/main/java/com/vzome/core/algebra/ParameterizedField.java
core/src/main/java/com/vzome/core/algebra/PentagonField.java
core/src/main/java/com/vzome/core/algebra/PolygonField.java
core/src/main/java/com/vzome/core/algebra/RootThreeField.java
core/src/main/java/com/vzome/core/algebra/RootTwoField.java
core/src/main/java/com/vzome/core/algebra/SnubDodecField.java
core/src/main/java/com/vzome/core/exporters/POVRayExporter.java
core/src/main/java/com/vzome/fields/sqrtphi/SqrtPhiField.java
core/src/test/java/com/vzome/core/algebra/AlgebraicFieldTest.java

There was no real value to using the algebraic expressions for ANs, and
this means we can get rid of AF.defineMultiplier(), which I have done.
I had to do quite a bit of debugging to get panels to work, and I finally
switched from "union { polygon { ..." to "mesh { triangle { ...".  This
way there is no problem with planarity of polygon vertices.

POV-Ray exporter now uses real numbers

---

core/src/main/java/com/vzome/core/editor/DocumentModel.java
desktop/src/main/java/org/vorthmann/zome/app/impl/ApplicationController.java

Until now, only new documents correctly saved the version info.
I also removed the irrelevant "coreVersion" and "edition" attributes.

Version info always saved

---

core/src/main/java/com/vzome/core/algebra/AbstractAlgebraicField.java
core/src/main/java/com/vzome/core/algebra/PlasticPhiField.java
core/src/main/java/com/vzome/core/algebra/PolygonField.java
core/src/main/java/com/vzome/fields/sqrtphi/SqrtPhiField.java
core/src/test/java/com/vzome/core/algebra/AlgebraicFieldTest.java

There is one small caveat when importing very large integers into the 10-gon field. This did not occur in the original prepareAlgebraicNumberTerms implementation when we did the remapping after all of the terms were BigRational, but now that we do the remapping while they are integers, we have this one virtually unavoidable regression. Still, it seems a small price to pay for supporting all possible fields online. I did not include a regression file related to this fix. Perhaps we can do that after fixing the bug parsing BigIntegers in the automatic directions of symmetries upon opening a vZome document.

Fix parse golden VEF into 5N-gon fields

---

core/src/main/java/com/vzome/core/tools/ProjectionTool.java
core/src/regression/files/2021/08-Aug/03-David-ProjectionTool-from-ball-and-strut/ProjectionTool-from-ball-and-strut.vZome
core/src/regression/files/sniff-test.vZome-files

A ProjectionTool can now be created from a strut that's normal to the projection plane and a ball on the plane.
The original way of creating a ProjectionTool from a panel and an optional strut still works the same as before.
A regression file is included which uses this new capability.

Create a ProjectionTool from a ball and strut

---

core/src/main/java/com/vzome/core/editor/DocumentModel.java
core/src/main/java/com/vzome/core/exporters2d/SnapshotExporter.java
desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java
desktop/src/main/java/org/vorthmann/zome/app/impl/Java2dSnapshotController.java

The "show background" checkbox was not respected when exporting, so the
background was always rendered.  The defect was only for export; the on-screen
rendering was correct.

Fixed 2d export background defect

---

core/src/jsweet/java/com/vzome/jsweet/JsAlgebraicField.java
core/src/main/java/com/vzome/core/algebra/AbstractAlgebraicField.java
core/src/main/java/com/vzome/core/algebra/AlgebraicField.java
core/src/main/java/com/vzome/core/algebra/SnubDodecField.java
core/src/main/java/com/vzome/core/edits/ImportMesh.java
core/src/main/java/com/vzome/core/math/VefParser.java
core/src/main/java/com/vzome/core/model/ColoredMeshJson.java
core/src/main/java/com/vzome/core/model/SimpleMeshJson.java
core/src/test/java/com/vzome/core/algebra/AlgebraicFieldTest.java

I moved the VefParser.fieldsAreCompatible() static method into AF as a
default method, so now it is called from the AF.Registry in ImportMesh.
ColoredMeshJson.parse() and SimpleMeshJson.parse() now test for a null
field, corresponding to incompatible fields.
I improved the error message in ImportMesh, for any exception.
The AAF.convertGoldenNumberPairs() base implementation now handles simple
extension of the array size to match the field order.
Most importantly, AAF.createAlgebraicNumberFromTD() now calls
convertGoldenNumberPairs() when appropriate.  To do this, it has to
convert from trailing divisors to pairs, and back again.
I also removed AF.createIntegerVectorFromTDs(), after I realized that
the JSON mesh imports could use AF.createVectorFromTDs, and it makes no
sense to create an …

Fixed the NPE when pasting golden JSON into sqrtPhi

---

online/src/wc/urlviewer.jsx
online/src/wc/vzome-viewer.css.ts

Material-UI was not building correctly, leaving the styles behind when
using esbuild, so I have simply hand-coded this, copying their styles and
SVG.  See vzome-viewer.css.ts.

Fixed the download button for vzome-viewer

---

online/src/wc/urlviewer.jsx
online/src/wc/vzome-viewer.js

MUI adds styles at runtime via JS, and by default they get added to the
HTML head.  I found a solution that adds them under the shadow root:
https://stackoverflow.com/questions/51832583/react-components-material-ui-theme-not-scoped-locally-to-shadow-dom

Material-UI is working again in the custom element

---

core/build.gradle

Since the jsweet Gradle plugin uses the "compile" configuration from the
Java plugin, it polluted the runtime classpath when I added JSweet and
its dependencies.  This is really a defect in the JSweet plugin.
I resolved it by making the dependency additions conditional on the task.

Removed log4j and other unneeded JARs from packaging

---

core/src/main/java/com/vzome/core/construction/Point.java
core/src/main/java/com/vzome/core/construction/Polygon.java
core/src/main/java/com/vzome/core/construction/Segment.java

The recent changes related to Construction.getSignature() cause a regression
in older vZome files that had 4D data.  Signatures were computed using
4D data, but compared with signatures already in the RealizedModel
computed using 3D data.

Fixed regression in older files

---

online/public/index.html
online/src/app/App.jsx
online/src/app/components/folder.jsx
online/src/ui/viewer/store.js
online/src/wc/vzome-viewer.js

Since the store dispatch to the worker is already async, it made much
more sense to hide the async nature within createWorkerStore().  This way
I can return the store synchronously, keeping client code simple.
I also (finally!) fixed the access pattern for built-in models, eliminating
the silly absolute paths.

Fixed the problem with async createWorkerStore

---

online/src/ui/viewer/store.js

Firefox (and older browsers) doesn't support module workers yet, and now
I detect that and put up an error alert.

Detecting Firefox for a better error experience

---

online/src/app/components/folder.jsx

The <input/> element was not getting reset, so selecting the same file
twice in a row did not trigger any event.

Fixed the local file defect

---

desktop/src/main/java/org/vorthmann/zome/app/impl/ApplicationController.java
desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java
desktop/src/main/java/org/vorthmann/zome/ui/ShareDialog.java
desktop/src/main/java/org/vorthmann/zome/ui/SymmetryToolbarsPanel.java

If the `share.last.mod.time` property is true, an opened file's last mod
time is used for the share timestamp.  By default, the current time will
be used, as before.
I also placed a maximum of 1600px on the image size for shares.

Share gesture can now use the original file mod date-time

---

online/src/ui/viewer/index.jsx
online/src/ui/viewer/store.js
online/src/wc/vzome-viewer.js
online/test/index.html

The "light DOM" generated for a `vzome-viewer` element is an `<img>` tag,
originally intended to show when Javascript is disabled, or any other
reason that the web component might not work.  By rendering a `<slot/>`,
we can also choose to show that content if anything goes wrong with
fetching, interpreting, and loading the 3D scene.
For example, this gives a better experience in Firefox, where the lack of
support for module workers means nothing will be rendered.

Using a shadow DOM slot to render fallback content

---

desktop/src/main/java/org/vorthmann/zome/app/impl/DocumentController.java

There was no property change fired for "original.path".

Fixing share button state

---

core/src/main/java/com/vzome/core/editor/ApplyTool.java

Since the legacy default is "true" when the attribute is missing, we have
to explicitly write "false".

Fixed a defect in serialization of ApplyTool copyColors

---

.github/workflows/test-and-regression.yml
.gitignore
cicd/jsweet-legacy-code.bash
core/src/jsweet/java/com/vzome/jsweet/JsAlgebraicField.java

I have also modified cicd/jsweet-legacy-code.bash to fail only when the
expected error output changes, and I've added this step to the test-and-
regression GitHub Actions workflow.
Hopefully this will prevent future failures of this nature.

Fixed JSweet transpile error from branch merge

---

desktop/src/main/java/org/vorthmann/zome/ui/ToolConfigDialog.java

The "behavior" tab is irrelevant, and thus removed.  The "show and select
parameters" is just the same as using the bookmark, so it is also removed.

Customized ToolConfigDialog for the bookmark case

---

desktop/src/main/java/org/vorthmann/zome/app/impl/ApplicationController.java

Previously, any AntiprismSymmetry would incorrectly open the pentagonal template without adjusting for the actual PolygonField

Handle "openTrackballModel" correctly for any AntiprismSymmetry

---

desktop/src/main/java/org/vorthmann/zome/ui/HyperlinkPanel.java
desktop/src/main/java/org/vorthmann/zome/ui/ShareDialog.java
desktop/src/main/resources/org/vorthmann/zome/ui/githubPostTemplate.md
desktop/src/main/resources/org/vorthmann/zome/ui/githubReadmeNoPostTemplate.md

1. The "View on GitHub" link required a full click, sometimes hard with
a mouse even, and especially hard with a trackpad.
2. That link could be broken if the filename started (or ended?) with
a hyphen.
3. Spaces in filenames caused havoc.

Fixed several bugs in GitHub sharing

---

ideas-today.txt
online/public/bhall/basic/index.html
online/public/browser/index.html
online/public/fivecell/index.html

There is no reason not to use the global path /modules, since that must
always exist to support the web component anyway.
I'm also committing my ideas-today.txt file, just for grins.

Fixing the module paths for the three separate apps

---

online/src/app/components/debugger.jsx
online/src/app/index.jsx
online/src/ui/viewer/index.jsx
online/src/ui/viewer/store.js
online/src/wc/mui-styles.css.js
online/src/wc/vzome-viewer.css.js
online/src/worker/legacy/js2jsweet.js
online/src/worker/vzome-worker-static.js

I've added SceneMenu to the DesignViewer component, as well as a
toggle to disable it.  It won't work for JSON previews, of course, so we
always fetch the actual XML now.  If the toggle is on, we replace
the preview scene seamlessly.
I have completely decoupled SCENE_RENDERED, so it stays uniform for all
use-cases.  The full, indexed DOM tree and possible article snapshots
are returned separately in DESIGN_INTERPRETED.

Supporting article/lesson viewing in vzome-viewer

---

online/src/app/bhall/basic/index.jsx
online/src/app/browser/browser.jsx
online/src/app/components/inspector.jsx
online/src/app/index.jsx
online/src/ui/viewer/index.jsx
online/src/worker/vzome-worker-static.js

In order to support showing snapshots with a preview JSON, the online
code was rendering twice, once for the preview and again after interpreting
the vZome XML.  In general we want to avoid that, since the interpretation
may have bugs.
Now parseAndInterpret() takes a new "render" argument that defaults to
true.  If a preview JSON was found and rendered, then we call
parseAndInterpret with render=false.
I also added a toggle to disable showing the snapshots menu.  This was
necessary for one of the bhall/basic models.  In the process, I added a
"config" property to the DesignViewer component and its wrappers,
subsuming the old "useSpinner" property.

Fixed the preview-then-interpret defect

---

online/src/app/index.jsx
online/src/ui/viewer/index.jsx
online/src/worker/vzome-worker-static.js

I'm reverting the changes that showed the scenes menu by default for
the viewer.  This causes regressions in existing pages, since the XML is
being interpreted now, and errors are arising.
I've also started passing the whole config through to the worker.

Fixing the preview failures

---

online/src/app/browser/browser.jsx
online/src/app/components/debugger.jsx
online/src/app/components/folder.jsx
online/src/app/index.jsx
online/src/ui/viewer/index.jsx
online/src/ui/viewer/store.js
online/src/wc/vzome-viewer.js
online/src/worker/vzome-worker-static.js
online/test/index.html

Web component users can now opt-in to `show-scene`.  If set, the vZome
XML will always be interpreted by the worker, and the DesignViewer will
show the scenes menu if any scenes are found.
I also tightened up the APIs at several levels.
First, `useVZomeUrl()` no longer takes a config param, going back to just
a `preview` parameter.  UrlViewer continues to have a `config` property.
I defined four action functions in the Redux store, notably `fetchDesign()`.
In the web component, I am being more careful about detecting actual attribute changes.
All apps have been tested.

Fixed the show-scene attribute for the web component

---

cicd/jsweet-legacy-code.bash
core/src/main/java/com/vzome/core/edits/SelectManifestation.java
core/src/main/java/com/vzome/core/tools/ScalingTool.java

JSweet is not clever enough when handling static methods from superclasses.
This change is a workaround, making the superclass name explicit.

Fixing transpilation bug in SelectManifestation

---

core/src/jsweet/java/com/vzome/jsweet/JsAlgebraicField.java
core/src/jsweet/java/com/vzome/jsweet/JsAlgebraicNumber.java
core/src/main/java/com/vzome/core/tools/TransformationTool.java
online/src/app/components/debugger.jsx
online/src/worker/fields/common.js
online/src/worker/legacy/js2jsweet.js
online/src/worker/legacy/jsweet2js.js

In js2jsweet.js, during interpretEdit(), just after loadAndPerform(), I'm
calling a new checkSideEffects(), which checks for an "effects" element
in the parsed txml.  If it finds it, it generates a new element using
edit.getDetailXml(), then stringifies and compares the two, throwing an
error if they don't match.
This required a correct implementation of JsAlgebraicNumber.toString(ZOMIC),
which further required a new toString() function on JS-implemented fields.
I also had to add enough DOM implementation to satisfy edit.getDetailsXml().
That included a JavaDomAttributes object that overrides toJSON() to sort
the attributes the same way DOM serialization would.
Note that I also had to make a correction to remove redundant
ColorManifestation side-effects during tool application.  This …

Diffing side effects when loading a history export

---

core/src/main/java/com/vzome/core/editor/SymmetrySystem.java
core/src/main/java/com/vzome/core/tools/SymmetryTool.java

This was a beast.
The defect was in SymmetryTool, where the switch statement wasn't handling
"synestructics" as a symmetry name.  That switch statement itself, of
course, is an egregious hack.  There should be subclasses for
OctahedralSymmetryTool and TetrahedralSymmetryTool.  Due to this missing
switch case, the tetrahedral symmetry case was falling through to the
default, producing 23 transformations rather than 11.
Furthermore, the defect was obscured on desktop vZome because the
ToolsModel map resolved a collision differently.  The ToolsModel pools
all tools from all SymmetrySystems, making the assumption that
"tetrahedral.whatever" means the same thing in all systems.
Due to the defect above, this was not true.  In the online code, the
Javascript implementation of ToolsModel resolved …

Fix tetrahedral symm defect in rootTwo for Online

---

online/src/ui/viewer/designcanvas.jsx

The `?vr=true` query parameter is no longer necessary.

Automatically sensing when VR is available

---

online/src/ui/viewer/designcanvas.jsx
online/src/ui/viewer/index.jsx
online/src/worker/vzome-worker-static.js

When viewing a web page with multiple vzome-viewer elements on the Oculus,
I want to be able to open any of the designs in VR, and currently only
one of the VRCanvas elements will work.
To solve this, I'm adding an "open in browser" button that launches vZome
Online in legacy preview mode.  It only shows if VR is available.
This also serves as a "preview" of the "open in vZome Online" that I
intend to provide for all viewers.

Preview button for VR mode

---

core/src/main/java/com/vzome/core/edits/ManifestationColorMappers.java
core/src/main/java/com/vzome/core/edits/MapToColor.java

Somehow, JSweet created SystemColorMap.applyTo(AV) without a return,
since it was overloaded with a method in the superclass.

Fixed JSweet transpile error due to method overloading

---

core/src/main/java/com/vzome/core/model/ManifestationImpl.java

Note: this may break some regression tests that compare history.
Manifestation.getXml() was exporting "NoConstructions" due to mutations
of the mManifests list later in the history.  A simple correction is to
always generate a Construction if the list is empty.
I need to do this in order to correctly compare the batch side-effects
export from Java with the incremental side-effects export in Javascript.
The incremental export happens before subsequent edits mutate the
mManifests lists, so it never generates "NoConstructions".

Corrected side-effects and history exporters

---

desktop/src/main/java/org/vorthmann/zome/ui/ShareDialog.java
desktop/src/main/resources/org/vorthmann/zome/ui/githubPostTemplate.md
desktop/src/main/resources/org/vorthmann/zome/ui/githubReadmeNoPostTemplate.md
desktop/src/main/resources/org/vorthmann/zome/ui/githubReadmeTemplate.md

The image is now fitting correctly in the same rectangle that the custom
element takes up, and we don't have doubled margins any more.
I also improved the commit message for GitHub share, using the post title.

Improved figure styling for vzome-viewer elements

---

desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java

Call System.exit() when UI can't initialize so that file locks and zombie processes are cleaned up.

Improve logging to help with migration to Java 17 on Windows

---

core/src/main/java/com/vzome/core/editor/Application.java
desktop/src/main/java/com/vzome/desktop/awt/ApplicationController.java
desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java

Since log file names are now generated at run time based on the version info in the build.properties resource files, their names showed up something like vZome-null.null_0_0.log when running in Eclipse, but not in the release builds or with gradlew run. I added comments about how to fix the build paths which Eclipse does not pick up automatically from build.gradle. I also added better logging when these resources are missing.
* Renamed some static final "logger" variables to use the conventional upper case "LOGGER".
* Added some missing @Override annotations

Add logging for missing build.properties and similar resources

---

core/src/main/java/com/vzome/core/kinds/DefaultFieldApplication.java
core/src/test/java/com/vzome/core/kinds/FieldApplicationTest.java

Somehow the refactoring got this wrong when I extracted the factories as
top-level classes.

Fixed registration of RotationToolFactory

---

core/src/main/java/com/vzome/core/exporters/ShapesJsonExporter.java

Manual export produced "foo.json" instead of "foo.shapes.json".  The
latter is consistent with Online preview logic.

Changed shapes.json file extension to match shares

---

core/src/main/java/com/vzome/core/edits/AdjustSelectionByClass.java

When all balls are being selected, AdjustSelectionByClass now has the same select-origin-last behavior that was recently added to SelectAll. AdjustSelectionByClass is generated by context menus on the parts tab.

Select origin last in AdjustSelectionByClass to match SelectAll behavior

---

cicd/jsweet-legacy-code.bash
online/build.gradle
online/public/testFields.html
online/src/worker/legacy/js2jsweet.js
online/src/worker/legacy/jsweet2js.js

First, the algebraicNumberFactory needed to be an actual class with the correct
`__interfaces`.  Second, the SnubDodecField(Application) was missing.
Finally, `JavaAlgebraicNumber` was missing the `toString(format)` method entirely.

Fixing defects in JS AlgebraicField implementations

---

.github/workflows/jsweet.yml

This action has to do all the same JSweet tool and library builds that the Online build does.

Fix JSweet action

---

online/src/ui/viewer/designcanvas.jsx
online/src/ui/viewer/index.jsx
online/src/ui/viewer/store.js

This is a workaround, and a partial one... it does not address the same behavior
issue with window resize.

Fixing the issue toggling full-viewport while in orthographic mode

---

.gitignore
cicd/build-online.bash
cicd/jsweet-legacy-code.bash
desktop/src/main/java/com/vzome/desktop/awt/DocumentController.java
desktop/src/main/java/com/vzome/desktop/controller/SymmetryController.java
desktop/src/main/java/com/vzome/desktop/controller/ToolController.java
desktop/src/main/java/com/vzome/desktop/controller/ToolsController.java
online/public/App.css
online/src/app/classic/classic.jsx
online/src/app/classic/components/toolbars.jsx
online/src/app/classic/controller-hooks.js
online/src/app/classic/orbit-panel.jsx
online/src/ui/viewer/store.js
online/src/worker/legacy/controllers.js
online/src/worker/legacy/core.js
online/src/worker/vzome-worker-static.js

I'm discarding the MUI Grid, since I need full control.  I'm using CSS grid layout,
even though I just use it in one dimension at a time, since the mechanism of
`gridTemplateRows` etc. is clear and simple.
I switched from '/' to ':' for controller path separator, because tool controllers
can have names that include '/'.  I also created the subcontroller() function
in store.js, so there is one place to control this on the client side.
I had to work around a JSweet transpiler defect that manifests in j4ts, for
LinkedHashMap:
https://github.com/cincheo/jsweet/issues/740
Status: the tool factory bar and tool bar are both rendering well, though the style
is quite dated.  I haven't attempted the build/parts/measure tabs yet, or anything
for the length controls.

Laying out components for the classic editor

---

core/src/main/java/com/vzome/core/kinds/HeptagonFieldApplication.java
core/src/main/java/com/vzome/core/kinds/IcosahedralSymmetryPerspective.java
core/src/main/java/com/vzome/core/kinds/OctahedralSymmetryPerspective.java
core/src/main/java/com/vzome/core/kinds/PolygonFieldApplication.java
core/src/main/java/com/vzome/core/kinds/RootThreeFieldApplication.java
core/src/main/java/com/vzome/core/kinds/RootTwoFieldApplication.java
core/src/main/java/com/vzome/fields/sqrtphi/SqrtPhiFieldApplication.java

* RotationToolFactory was accidentally replaced with SymmetryToolFactory in createToolFactories() of all FieldApplications at commit 9e09b72b4982117c4fad92df131676e04e3ac70a

Fix: Missing rotation tool factory icons

---

core/src/main/java/com/vzome/core/editor/DocumentModel.java
core/src/main/java/com/vzome/core/editor/SelectionImpl.java
core/src/main/java/com/vzome/core/editor/SelectionSummary.java
core/src/main/java/com/vzome/core/editor/api/ChangeSelection.java

An example of a file with the problem that is fixed by this PR can be found at https://gist.githubusercontent.com/david-hall/de899b729b1a4a067146eb6d51998090/raw/8ccd4185244396cf03f2a32ba39ba21130550897/unrecorded-DeselectAll-after-Failure.vZome.
It can't be opened in desktop and it can't be fully executed in the online debugger.
Read the snapshot comment within that file for an explanation of how to reproduce the problem and the solution I have implemented here.
This fix doesn't allow existing files with the problem to be opened, nor does it identify files having the problem, but it does avoid generating such files in the future.

Fix missing DeselectAll after failure of any edit with orderSelection =  true

---

desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java

This fixes an issue that initially showed up when we switched desktop to Java 17. The main window is correctly maximized at startup, but when it's later switched to normal size (not maximized or minimized) then it was much bigger than the actual screen, at least on Windows 10. I'm not sure about the MAC. The solution is to set the "normal" size after the frame is made visible in the same way as commit 0ff6a4f41ac0d655c203930b5b0a9ba04d215267 did for the maximized window state.

Fix: Non-maximized window size too big at startup

---

online/src/ui/viewer/designcanvas.jsx
online/src/ui/viewer/geometry.jsx

The default r3f render loop chews up CPU, and people notice the fan
starting up.  I've taken over the rendering, as instructed by r3f's
`useFrame()` documentation.  It works OK, though it may need more
work when edits are happening.
I think it may give a bit of jank while zooming, but it is hard to tell.

Took over rendering for better performance

---

core/src/main/java/com/vzome/core/kinds/HeptagonFieldApplication.java
core/src/main/java/com/vzome/core/kinds/IcosahedralSymmetryPerspective.java
core/src/main/java/com/vzome/core/kinds/OctahedralSymmetryPerspective.java
core/src/main/java/com/vzome/core/kinds/RootThreeFieldApplication.java
core/src/main/java/com/vzome/core/kinds/RootTwoFieldApplication.java
core/src/main/java/com/vzome/fields/sqrtphi/SqrtPhiFieldApplication.java

All field applications except PolygonField were incorrectly generating a SymmetryTool instead of a RotationTool for the predefined tool labeled "rotate around red (or green) through origin" or "fivefold rotation through origin".
This bug was introduced in version 7.1.5 commit 9e09b72b4982117c4fad92df131676e04e3ac70a

Fix: built-in rotation tool invokes wrong ToolFactory

---

online/public/test/index.html
online/src/app/buildplane/buildplane.jsx
online/src/app/buildplane/index.jsx
online/src/app/buildplane/planes.js
online/src/ui/viewer/store.js
online/src/worker/vzome-worker-static.js

I have created
a `fallbackStore` notion to allow the buildplane store to react directly
to the worker responses.  This fixes the "red plane => octahedral symm."
bug.  I've also implemented a better plane-center state, based on the
same idea; FETCH_STARTED now always gets emitted, even for a new design.

Better worker integration for buildplane

---

online/src/ui/viewer/designcanvas.jsx

I did not have the `trackballChange` and `trackballEnd` handlers
connected in VR mode, and for some reason Android mobiles always
offer immersive VR mode, except when accessing my dev server.
I've also removed orthographic rendering, which is just full of bugs.

Fixed the Android browser trackball touch problem

---

core/src/main/java/com/vzome/core/editor/AbstractToolFactory.java

This defect is really dumb, because the tools model implementation
is really dumb.  We are emitting change events during deserialization
of hidden tools.
Fortunately, it seems to be save to call `setCategory()` before the
`setConfiguration()` call, which unfortunately has side-effects.

Fixing regression in core tool deserialization

---

desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
online/build.gradle
online/src/app/classic/appbar.jsx
online/src/app/classic/classic.jsx
online/src/app/classic/components/menuaction.jsx
online/src/app/classic/components/menubar.jsx
online/src/app/classic/menus/constructmenu.jsx
online/src/app/classic/menus/editmenu.jsx
online/src/app/classic/menus/filemenu.jsx
online/src/app/classic/menus/help.jsx
online/src/app/classic/menus/systemmenu.jsx
online/src/app/classic/menus/toolsmenu.jsx
online/src/worker/legacy/controllers.js
online/src/worker/legacy/core.js
online/src/worker/vzome-worker-static.js

I added the missing setEditorModel() calls for symmetrySystems,
and I removed the useless DefaultController, replacing it with the
EditorController.
I've also added proper error reporting, and added the System menu,
though it is all disabled at the moment.  The Help menu is now there, too.
ReplaceWithShape (tools menu) still does not work, so it is disabled.
I've also updated the Help menu links in desktop, to avoid the old blog.

WIP Enabling more menu commands in classic

---

core/src/main/java/com/vzome/core/algebra/AlgebraicFields.java
core/src/main/java/com/vzome/core/algebra/SnubDodecahedronField.java
core/src/test/java/com/vzome/core/algebra/AlgebraicFieldTest.java
core/src/test/java/com/vzome/core/algebra/ParameterizedFieldTest.java

Equivalent to the legacy SnubDodecField but derived from ParameterizedField.
Now all of the legacy fields have a comparable ParameterizedField.
This class is not used anywhere yet, but it's been implemented for a long time and I wanted to get it into the code base just for completeness.
This is also a necessary step towards refactoring and merging ParameterizedField into AbstractAlgebraicField.

Add SnubDodecahedronField

---

core/src/main/java/com/vzome/core/commands/CommandUniformH4Polytope.java

There were two issues that were OK in Java, but caused problems when
transpiled via JSweet.

CommandUniformH4Polytope defect fixes

---

online/public/classic/index.html
online/public/index.html
online/src/app/components/folder.jsx

It is only enabled if you do:
`localStorage.setItem( 'vzome.enable.dropbox', true )`
in the browser console

Dropbox chooser integrated to classic and online

---

online/src/app/components/folder.jsx

Add `?enableDropbox=true` to enable on a mobile phone, where
you typically cannot type into a console.  It will be stored in localStorage,
per origin.

Can enable Dropbox with query param

---

.github/workflows/jsweet.yml

This means David can let GitHub do the JSweet build, rather than setting
up all four modified projects locally, and just download the archive
for local testing.

Correct archive path for JSweet action

---

desktop/src/main/java/com/vzome/desktop/awt/DocumentController.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java

Now the ".vZome" extension is correctly stripped off, and the
correct extension is applied based on the exporter.

Corrected save.exports file naming defects

---

build.gradle
core/build.gradle
desktop/build.gradle

Since this is now published on a real Maven repo, unlike the release
candidates, we can use the documented "-main" packages.  Maybe
we could have before, too... not sure.

Updated to JOGL 2.4.0 release

---

desktop/src/main/java/org/vorthmann/zome/render/jogl/JoglOpenGlShim.java

I'd like to be able to find out what OpenGL version some of our most prolific users have on their computers. This is a first step.

Add OpenGL version logging at startup

---

desktop/src/main/java/org/vorthmann/zome/ui/ControllerFileAction.java

Avoids file extensions such as Foo.vzome.vZome due to user provided extension differing only in upper/lower case.

Avoid multiple repeated file extensions

---

desktop/src/main/java/com/vzome/desktop/controller/SymmetryController.java
online/src/app/classic/classic.jsx
online/src/app/classic/components/length.jsx
online/src/app/classic/components/orbits.jsx
online/src/app/classic/components/shapes.jsx
online/src/app/classic/components/strutbuilder.jsx
online/src/app/classic/components/toolbars.jsx
online/src/workerClient/controllers-solid.js

The orbits config dialog was broken, missing a controller definition.
The shapes dialog was initially uncontrolled, and also not getting change events.
The useSymmetry() context now includes "symmetryDefined()", so UIs can avoid trying
to get properties from "symmetry.undefined", and so on.
I fixed some wrong properties in the orbits control dialog.
I corrected  a nasty bug in controller-solid.js, wherein controllerProperty() was treating
a false-valued property like an undefined one!  This caused an infinite loop when
I hit "none" on the availableOrbits panel.

Defect fixes

---

online/public/test/index.html
online/src/viewer/solid/index.jsx
online/src/wc/vzome-viewer.js
online/src/worker/legacy/controllers/index.js
online/src/worker/vzome-worker-static.js

This will allow programmatic scene selection.  Scene titles are discoverable by subscribing
to the "vzome-scenes-discovered" CustomEvent, emitted by the viewer element.
See `online/public/test/index.html` for sample code.
A scene index, rather than a title, can be selected as "#6" for index 6, zero-based.
Invalid title or index will result in a console warning message, and display of the default scene.
The `show-scenes` attribute is irrelevant when the scene attribute is set; the viewer is
thus scene-controlled and the scenes menu won't be displayed.

Scene attribute on web component

---

online/src/worker/vzome-worker-static.js

If a preview JSON was found, but no scene was requested, the load failed.

Fixed critical defect for missing scene attribute

---

online/src/wc/vzome-viewer.js
online/src/workerClient/actions.js
online/src/workerClient/controllers-solid.js

Since the user can enter any text into the article page titles in desktop vZome, the
serialized XML may contain entities that encode those characters, e.g. "&" becomes "&amp;".
The XML parser normally reverses this, but the `txml` parser I'm using in the worker does
not!  This will be even more important when other languages are used.
The fix is simple, and is done in the main context, where I can leverage the DOM parsing
and decoding of entities.  I do have to do the decoding twice, once for each worker
subscriber, and I have to encode when sending SCENE_SELECTED.

Fixing the use of XML entities in scene titles

---

.gitignore
cicd/build-online.bash
online/src/app/classic/components/length.jsx
online/src/app/classic/components/toolbars.jsx
online/src/app/classic/components/toolconfig.jsx
online/src/worker/vzome-worker-static.js

The path has to be "./resources/...", always relative to window.location, even
within the worker, where window.location must be passed in.
I also fixed a defect in build-online.bash, which was not cleaning up dev modules.

Corrected the defect in resource paths

---

online/src/app/buildplane/buildplane.jsx
online/src/app/classic/components/appbar.jsx
online/src/app/classic/components/camera.jsx
online/src/app/classic/index.jsx
online/src/viewer/solid/ltcanvas.jsx
online/src/worker/vzome-worker-static.js

Appbar layout was assuming classic, broken for online, browser, buildplane, etc.
I moved the menus & persistence title to an injected "spacer" slot for appbar.
Apps are now working, except for issues below.
The architecture for connectTrackballScene is finally right, using a special
controller action triggered in an effect from the Camera component.
Spurious trackball change events causing width=NaN is fixed, by making sure
that the callback only happens in the main LightedTrackballCanvas.
- no alert showing in apps
- open-change-save-reopen bug, losing parts of history

Fixing bugs in non-classic apps

---

online/src/app/classic/components/nosave.jsx
online/src/app/classic/menus/filemenu.jsx

Edit history is not serialized correctly.  Every classic design saved already is suspect,
so we don't want to make more of them.

Saving designs temporarily disabled

---

online/src/app/classic/components/beta.jsx
online/src/app/classic/menus/filemenu.jsx
online/src/worker/legacy/controllers/index.js
online/src/worker/legacy/core.js
online/src/worker/legacy/edit.js
online/src/worker/legacy/interpreter.js
online/src/worker/legacy/parser.js

The interpreter was simply not adding branches to the history, since it wasn't built
to faithfully reproduce the history for saving again.
I split EditCursor out of RenderHistory, since they really are different functions.
I still want to merge interpret() and EditCursor into "Interpreter", but that can wait.
The EditCursor already cleans up the interpreter step() function a fair bit.
RenderHistory is no longer able to perform interpret() in order to render a scene
that was not captured yet, as when the debugger is in use.  I'll have to do more
refactoring to make that work, and it needs more thought.
RenderHistory could be optimized (for non-debugger use) to only capture scenes
for snapshots and the targetEdit state.
I renamed LegacyEdit as ParsedEdit.
I added a Beta Version warning …

Fixed interpreter branch history bug

---

online/src/worker/legacy/core.js
online/src/worker/vzome-worker-static.js

The design name is only set when the interpreter has succeeded.
I added a specific error for RunZomicScript commands.

Better error handling on open / openURL

---

online/src/app/classic/components/camera.jsx
online/src/app/classic/menus/contextmenu.jsx
online/src/viewer/solid/ltcanvas.jsx
online/src/viewer/solid/rotation.jsx
online/src/viewer/solid/scenecanvas.jsx
online/src/viewer/solid/trackballcontrols.jsx
online/src/workerClient/context.jsx

The trackball and main view now stay in sync.
I had to change `RotationContext` to use cameraState rather than a quaternion, so that
`useCopiedView` could `publishRotation`.
I also did some refactoring to move logic out of `trackballcontrols.jsx` and `ltcanvas.jsx`.
I also controlled the trackball rotation speed better.

Fixed camera defects

---

core/src/main/java/com/vzome/core/algebra/AbstractAlgebraicField.java
core/src/main/java/com/vzome/core/algebra/AlgebraicNumberImpl.java
core/src/main/java/com/vzome/core/algebra/BigRationalImpl.java
core/src/main/java/com/vzome/core/algebra/Fields.java
core/src/test/java/com/vzome/core/algebra/AlgebraicNumberTest.java
desktop/src/main/java/com/vzome/desktop/controller/LengthController.java
online/src/app/classic/components/length.jsx
online/src/worker/fields/common.js
online/src/worker/fields/golden.js
online/src/worker/fields/heptagon.js
online/src/worker/fields/root2.js
online/src/worker/fields/root3.js
online/src/worker/java/com/vzome/jsweet/JsAlgebraicField.java
online/src/worker/java/com/vzome/jsweet/JsAlgebraicNumber.java
online/src/worker/legacy/jsweet2js.js

Every Field.Element (like AN or BR) now supports `getMathML`.  The result is ready to
be placed inside `<math>...</math>` or any other bit of MathML.  A `<mrow>` is
automatically added when necessary.
Along the way, I corrected the use of `getIrrational` in the JS field implementations.
Finally, the MathML output is now used in Online classic, to display the final strut length.

Adding MathML support

---

online/package.json
online/src/viewer/solid/export.jsx
online/src/viewer/solid/geometry.jsx
online/src/viewer/solid/index.jsx
online/src/viewer/solid/ltcanvas.jsx
online/yarn.lock

I had to update `three-stdlib` to get a version of the exporter that worked.  I tried updating
`three.js` also, but it changed the lighting, so I reverted that.
The glTF export mostly works, but the single `buffer` object comes out with just a `byteLength`
property and nothing else... no data.  I'll have to step through the code to see why.

Restored glTF exporter in vzome-viewer

---

.gitignore
online/src/viewer/solid/geometry.jsx

The GltfExportContext needed a complete default, for use in Classic.
TODO: add the glTF export to the file menu

Fixed new defect in classic

---

online/src/app/59icosahedra/index.jsx

I don't really know what's happening, but this change gives a much wider range of aspect ratios
that lay out correctly.  It still goes bad for portrait mode on a phone.

Restore left-side grid layout to fix aspect ratio bug

---

online/src/worker/legacy/controllers/index.js
online/src/worker/vzome-worker-static.js

The `vzome-legacy` module was importing `getSceneIndex` from the static worker
module, which is also the module that imports `vzome-legacy` dynamically.  This
is harmless in normal situations, but disastrous in the "quick" workflow, which loads
the dynamic module from `vzome.com`.  It results in very odd behavior, since two
copies of the same module are present at runtime.
This change is the most obvious, simple way to fix the dependency, but needing the
`getSceneIndex` function in both places does point at a leaking abstraction boundary.

Removing circular module dependency

---

online/public/test/regression.html
online/src/viewer/solid/index.jsx
online/src/viewer/solid/ltcanvas.jsx
online/src/viewer/solid/perspectivecamera.jsx
online/src/wc/vzome-viewer.js
online/src/worker/vzome-worker-static.js
online/src/workerClient/camera.jsx

The default value is `always`, which produces the existing behavior, where the
camera loaded from a design overwrites the current camera state.  A value of `once`
means that that happens on the first design load, but not thereafter... the camera
state will remain undisturbed by loading a design.  Any other value equates to `never`.
I also removed some logging left over from the camera state work.

Implemented `load-camera` attribute on web component

---

online/public/test/index.html
online/public/test/vzome-viewer.css
online/src/viewer/solid/index.jsx
online/src/wc/vzome-viewer.js
online/src/worker/vzome-worker-static.js
online/src/workerClient/actions.js

Now you can set `reactive` (attr or prop) to `false`, and then do `update( load )`
when you're done changing things.  The parameter to `update()` takes the form
`{ camera: true, lighting: true, design: true }`, with those being the default.
Load control is implemented in the worker, using `filterScene()`.
Also, the component tracks whether the `src` URL or the `scene` title has been
changed since the last `fetchDesign` or `selectScene` message was sent.
The `selectScene` message now accepts an optional load configuration.
I've updated the web component test page to replicate my CodePen sandbox
for dynamic viewer control, except with `reactive` turned off, and an explicit
`update()` call.

Improved vzome-viewer API

---

online/public/test/index.html
online/public/test/models/test-show-scenes.shapes.json
online/src/app/59icosahedra/selectors.jsx
online/src/app/59icosahedra/state.jsx
online/src/viewer/context/viewer.jsx
online/src/viewer/geometry.jsx
online/src/viewer/index.jsx
online/src/viewer/labels.jsx
online/src/viewer/ltcanvas.jsx
online/src/wc/vzome-viewer.js

Everything is working correctly, and the labels show up in the selector panels for
`59icosahedra`.  Both the developer and the `vzome-viewer` author have
control over whether labels are shown.
No authoring support in desktop yet... it is necessary to hand-edit `.shapes.json`.

Added support for labels in the scene

---

online/public/test/index.html
online/src/viewer/index.jsx
online/src/wc/vzome-viewer.js

Dev use-case is more expected: `viewer.showPerspective=false;`

Added `show-perspective` attribute to web component

---

desktop/src/main/java/org/vorthmann/zome/ui/ShapesDialog.java

"Vienne 121 zone" and the new "dimtool" styles were not visible because the dialog was a fixed height that was too short for them.

Adjust Shapes dialog height to display all styles

---

core/src/main/java/com/vzome/core/exporters/GitHubShare.java
online/public/test/index.html
online/src/wc/index-buttons.js
online/src/wc/vzome-viewer.js

The customized built-in buttons didn't work in Safari, and may never work.
See the compatibility note in the MDN browser support table.

Viewer index buttons now custom elements

---

online/public/test/vzome-viewer-styles.css
online/src/viewer/index.jsx
online/src/viewer/urlviewer.css.js

Page authors can provide `vzome-viewer-styles.css`, optionally.

Support external style overrides for vzome-viewer

---

.gitignore
online/public/test/index.html
online/src/wc/index-buttons.js

The default for `load-camera` is false, for backward compatibility.

Viewer index buttons now support load-camera

---

online/src/app/classic/dialogs/svgpreview.jsx
online/src/app/classic/menus/filemenu.jsx

- the current parameters are now passed to the export
- the default export gestures now use the outlines state
- the preview dialog uses the outline state, and regenerates without being
reactive to camera changes

Fixes for vector graphics capture

---

online/src/app/classic/components/appbar.jsx
online/src/app/classic/components/editor.jsx
online/src/app/classic/components/toolbars.jsx
online/src/app/classic/dialogs/sharing.jsx
online/src/app/classic/dialogs/webloader.jsx
online/src/app/classic/index.jsx
online/src/app/classic/menus/editmenu.jsx
online/src/app/classic/menus/filemenu.jsx
online/src/app/framework/menus.jsx
online/src/viewer/context/editor.jsx

The Kobalte dropdown menus get created and destroyed on each use, so it is
inappropriate to register key event listeners each time!

Eliminated redundant menu keyboard listeners

---

online/public/test/cases/indexed-viewer/index.html
online/public/test/cases/zometool-instructions/index.html
online/public/test/cases/zometool-instructions/styles.css
online/public/test/index.html
online/scripts/esbuild-config.mjs
online/src/app/classic/menus/contextmenu.jsx
online/src/viewer/context/camera.jsx
online/src/viewer/index.jsx
online/src/wc/index-buttons.js
online/src/wc/vzome-viewer.js
online/src/wc/zometool.css.js
online/src/wc/zometool.jsx

I have added "start" and "end" button components, though I don't expect to use them
for the Zometool pages.  The "end" button, in particular, is not good for leaving an
"instructions" mode, since it is disabled on the last scene.  I was using them in the
`indexed-viewer` test page, but decided to have explicit, custom mode buttons instead;
they use the new `selectScene()` viewer method.
I have a SolidJS component, `ZometoolInstructions`, and a web component.
Everything works.

Implemented instructions web component for Zometool

---

core/src/main/java/com/vzome/core/render/JsonMapper.java
online/public/test/cases/zometool-instructions/all-parts.vZome
online/public/test/cases/zometool-model/index.html
online/src/viewer/context/viewer.jsx
online/src/wc/zometool/bom.js
online/src/worker/fields/common.js
online/src/worker/legacy/interpreter.js
online/src/worker/legacy/partslist.js
online/src/worker/legacy/preview.js
online/src/worker/legacy/scenes.js

Desktop vZome will now add `orbitC` and `length` fields to `.shapes.json`
previews, containing the canonical orbit name and the canonical length, respectively.
When normalizing the preview in vZome Online, `orbitC` is renamed as `orbit`.
Panel shapes have no metadata, and ball shapes have just `name==='ball'`.
I'm not removing the old `name` and `orbit` fields from the legacy desktop
preview format, in case the folks in China use that information to derive their BOMs.
Zometool parts-list (BOM) computation is now expecting a parts table whose keys
are 'ball' or `${orbit}:${length}`, from a normalized shape.
The normalized shape format is created directly when interpreting XML.

Normalized shape identities for complete BOM support

---

desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java

If you were not getting "white window" crashes for vZome, turn this on to have much
better performance.

Exposed vzome.jogl.heavyweight.canvas preference

---

desktop/src/main/java/org/vorthmann/j3d/Platform.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java

I don't want Windows and Linux users to pay the performance penalty, when the
defect we are avoiding is only on Macs.

Only macs will use lightweight GLJPanel for the main view

---

core/src/main/java/com/vzome/core/construction/LineReflection.java
core/src/regression/files/2024/07-Jul/25-David-LineReflection-BugFix/BugFix-LiineReflectionTool.vZome
core/src/regression/files/sniff-test.vZome-files

NPE thrown when axis was not collinear with origin because line-line intersection was calculated with an incorrect line (missing offset).
Includes new regression file exhibiting the conditions to generate the bug.

Fix bug in LineReflectionTool

---

online/src/viewer/context/camera.jsx

The width factor did not match desktop, which caused a subtle defect when
switching scenes whose camera positions were different.  The trackball update
caused the camera width to be recomputed with the wrong factor.  This made
a subtle "zoom" effect.

Fixed WIDTH_FACTOR bug

---

online/src/app/browser/browser.jsx
online/src/app/browser/users.jsx

A mixed-case username as a query parameter would cause a null entry from
the select component.  Now we lowercase the query parameter right away.

Fixed username case defect in GitHub browser app

---

core/src/main/java/com/vzome/core/exporters/POVRayExporter.java

Almost a year ago, for `online-r161`, I introduced an API change for the
Lights class, but I didn't adapt the POV-Ray exporter code correctly.  This
corrects that oversight.

Fixed a bug in the POV-Ray exporter

---

cicd/jsweet-legacy-code.bash
cicd/online.bash
core/src/main/java/com/vzome/core/editor/DocumentModel.java
core/src/main/java/com/vzome/core/exporters/DocumentExporter.java
core/src/main/java/com/vzome/core/exporters/DocumentIntf.java
core/src/main/java/com/vzome/core/exporters/GeoGebraExporter.java
core/src/main/java/com/vzome/core/exporters/GeometryExporter.java
core/src/main/java/com/vzome/core/exporters/HistoryExporter.java
core/src/main/java/com/vzome/core/exporters/OpenScadExporter.java
core/src/main/java/com/vzome/core/exporters/POVRayExporter.java
core/src/main/java/com/vzome/core/exporters/PartGeometryExporter.java
core/src/main/java/com/vzome/core/exporters/SideEffectsExporter.java
core/src/main/java/com/vzome/core/viewing/Camera.java
core/src/main/java/com/vzome/core/viewing/CameraIntf.java
online/README.md
online/build.gradle
online/src/worker/java/java/io/File.java
online/src/worker/legacy/candies/j4ts-2.1.0-SNAPSHOT/bundle.js
online/src/worker/legacy/controllers/editor.js
online/src/worker/legacy/core-java.js
online/src/worker/legacy/exporters.js

I did the necessary Java refactoring to allow `PovRayExporter.java` and some
others to transpile with JSweet.  This involved introducing `DocumentIntf` and
`CameraIntf`.
I did some of the work on the Javascript side, but I haven't completed the
key `createDocument` function to create the DocumentIntf instance yet.
Along the way, I noticed that PartGeomExporter probably does not work on
the Java side, since its `exportDocument()` method won't be called.

Porting POV-Ray and other exporters

---

online/src/app/browser/github.js

It was apparently in place to show only shares that had preview .shapes.json files.

Removed the filter for the GitHub browser app

---

.devcontainer/devcontainer.json
online/scripts/test-app.mjs
online/src/worker/vzome-worker-static.js

The legacy module (at r114) is dynamically imported from vzome.com.
This lets me run the quick workflow in a devcontainer, and debug the inspector code.  I need this because I need to match the scene protocol used in this old branch, so I can make the old inspector client code work against modern worker code.

Supporting quick workflow with inspector/debugger

---

.github/workflows/desktop.yml

Use of the macos-12 image is not viable any more.

Attempt to fix intel build

---

online/serve/app/test/cases/zometool-model/index.html
online/src/worker/legacy/partslist.js

Any file written by desktop vZome did not match (I think), because the hex codes
are serialized in uppercase.

Fixed case sensitivity in BOM color tests

---

desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java

Defaulting to lightweight canvas on Windows fixes this bug. It's probably not the actual problem, but this is a quick and easy work-around for now.

Fix Windows display scaling bug

---

.gitattributes
cicd/online.bash
online/README.md

1) Fix the shebang for the .bash script that's used by VSCode. The shebang of other scripts may need to be modified similarly later, but that will be done on an as-needed basis.
2) Ensure that git applies the correct line ending (LF) for all .bash files when they are checked out rather than having them be OS dependent.
3) Clarify local VSCode instructions

Fixes to let VSCode run online in a local Docker container in Windows

---

core/src/test/java/com/vzome/core/exporters/ExporterTest.java
core/src/test/java/com/vzome/core/kinds/FieldApplicationTest.java

Now that very short green struts don't generate a shape, these two unit tests
need to be adjusted.

Fixed failing unit tests

---

core/src/main/java/com/vzome/core/editor/DocumentModel.java
desktop/src/main/java/com/vzome/desktop/awt/DocumentController.java

This enables me to get simple mesh JSON without the silly last-object
offset, or rather letting me control the last object as the origin.

Added copy.mesh action

---

.vscode/launch.json
core/src/main/java/com/vzome/core/algebra/AbstractAlgebraicField.java
core/src/main/java/com/vzome/core/edits/ImportSimpleMeshJson.java
core/src/main/java/com/vzome/core/model/SimpleMeshJson.java
core/src/test/java/com/vzome/core/apps/Dump4dPolytopeVson.java
online/src/worker/java/com/vzome/jsweet/JsAlgebraicField.java
online/src/worker/legacy/core-java.js
online/src/worker/legacy/core.js
online/src/worker/legacy/ts/com/vzome/core/algebra/AbstractAlgebraicField.ts
online/src/worker/legacy/ts/com/vzome/core/editor/SymmetrySystem.ts
online/src/worker/legacy/ts/com/vzome/core/edits/ReplaceWithShape.ts
online/src/worker/legacy/ts/com/vzome/core/render/RenderedModel.ts
online/src/worker/legacy/ts/com/vzome/jsweet/JsAlgebraicField.ts
online/src/worker/legacy/ts/core-java.ts

The command now serializes with `scaleAndProject="true"` by default,
so that older files (without it) will open as before.
Online vZome has the same functionality, though it still has no UI for setting
scale and quaternion.

Simple Mesh JSON imports support scale and rotate

---

core/src/test/java/com/vzome/core/exporters/ExporterTest.java

The recent addition of half green struts requires undoing the change to the Exporter unit test in commit 44ad64b53770357e60495d00b54731a7f867fad9. The original unit test is now working again.

Fix failing unit test

---

online/src/app/classic/context/commands.jsx
online/src/app/classic/menus/filemenu.jsx
online/src/app/framework/context/editor.jsx

I also enabled online vZome to "save" directly, since I now trust the serialization to not
lose data.
I fixed a defect wherein the design name would be ignored forever after one ignored
file load (help, or Dropbox, or open-as-new).

Added "open as new design"

---

core/src/main/java/com/vzome/core/edits/ImportSimpleMeshJson.java

Was using `wFirst=true`, which was incorrect, for legacy documents (no
`scaleAndProject` behavior).

Fixed simple mesh JSON import

---

core/src/main/java/com/vzome/core/kinds/AbstractSymmetryPerspective.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
online/src/worker/legacy/core-java.js
online/src/worker/legacy/ts/com/vzome/core/editor/SymmetrySystem.ts
online/src/worker/legacy/ts/com/vzome/core/edits/ReplaceWithShape.ts
online/src/worker/legacy/ts/com/vzome/core/kinds/AbstractSymmetryPerspective.ts
online/src/worker/legacy/ts/com/vzome/core/render/RenderedModel.ts
online/src/worker/legacy/ts/core-java.ts

The icosa-, octa-, and tetrahedral symmetry menu commands are now added with
the correct conditionality, and applied with the correct controller.  The menu does
not need to change when the symmetry system changes, therefore.
The online UI still needs to be updated similarly.

Better support for symmetry menu commands

---

core/build.gradle
core/src/main/java/com/vzome/api/Application.java
core/src/main/java/com/vzome/core/exporters/GitHubShare.java
core/src/main/java/com/vzome/core/exporters2d/Java2dSnapshot.java
core/src/main/java/com/vzome/core/kinds/AbstractSymmetryPerspective.java
core/src/main/java/com/vzome/core/viewing/SchochShapes.java
core/src/regression/java/com/vzome/core/regression/TestVZomeFiles.java
core/src/test/java/quickhull3d/QuickHull3D.java
desktop/build.gradle
desktop/src/main/java/com/vzome/desktop/awt/ApplicationController.java
desktop/src/main/java/org/vorthmann/j3d/Platform.java
desktop/src/main/java/org/vorthmann/zome/render/jogl/JoglRenderingViewer.java
desktop/src/main/java/org/vorthmann/zome/ui/ApplicationUI.java
desktop/src/main/java/org/vorthmann/zome/ui/ContextualMenu.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentFrame.java
desktop/src/main/java/org/vorthmann/zome/ui/DocumentMenuBar.java
desktop/src/main/java/org/vorthmann/zome/ui/MeasurePanel.java
desktop/src/main/java/org/vorthmann/zome/ui/PartsPanel.java
desktop/src/test/java/org/vorthmann/zome/render/jogl/View3dActivity.java

All "this-escape" warnings are just ignored for now. All other warnings are fixed except for the unavoidable deprecation warnings in the zomic test cases.

Cleanup all Java Lint warnings after recently upgrading Java

---

online/src/app/classic/dialogs/svgpreview.jsx
online/src/worker/legacy/controllers/editor.js
online/src/worker/legacy/exporters.js

When I implemented POV-Ray export, I reused `createLights()`, but changed
it to use the `worldDirection` vector for each light, since that's what POV needs.
However, that function is also used for 2D export, which needs the view
coordinates.  I am now generating the world coordinates always, but only
using them for POV export.

Fixing 2D preview

---

online/src/app/classic/context/commands.jsx
online/src/app/classic/menus/toolsmenu.jsx
online/src/worker/legacy/controllers/editor.js
online/src/worker/legacy/core-java.js
online/src/worker/legacy/ts/com/vzome/core/editor/SymmetrySystem.ts
online/src/worker/legacy/ts/com/vzome/core/edits/ReplaceWithShape.ts
online/src/worker/legacy/ts/com/vzome/core/exporters/GitHubShare.ts
online/src/worker/legacy/ts/com/vzome/core/exporters2d/Java2dSnapshot.ts
online/src/worker/legacy/ts/com/vzome/core/kinds/AbstractSymmetryPerspective.ts
online/src/worker/legacy/ts/com/vzome/core/render/RenderedModel.ts
online/src/worker/legacy/ts/com/vzome/core/viewing/SchochShapes.ts
online/src/worker/legacy/ts/core-java.ts

First, I ran JSweet to catch up.
Everything now seems correct, and robust even if we have some field that
claims to not support octahedral symmetry.

Aligned symm commands in menu with desktop

---

online/src/viewer/cameramode.jsx
online/src/viewer/index.jsx
online/src/wc/gltf/index.jsx
online/src/wc/vrml/index.jsx

The toggle is hidden unless there is polygon information in the scene, or when
it is forcibly disabled, as for glTF or VRML.  Technically, the former would be
sufficient.

Outlines toggle now hidden when it is inoperative

---

.github/workflows/website.yml

Pages is now disabled, since the deployment will go to Dreamhost.

Removed GitHub Pages deployment

---

online/serve/app/localfiles/index.html
online/src/viewer/context/viewer.jsx
online/src/viewer/context/worker.jsx
online/src/viewer/index.jsx
online/src/wc/vzome-viewer.js

I added support for the `progress` attribute on the web component.
Also, it no longer creates the worker client, instead recording the viewer
context via a callback.  Part of this required exposing `subscribeFor` on
the viewer context.

Added scenes menu & progress bar for file browser

---

desktop/build.gradle

It took a while to find this solution, using a plugin that adapts p2 repos
for use in Maven and Gradle.

Sourcing EGit from p2 repo

---

online/serve/app/localfiles/index.html
online/src/worker/legacy/core-java.js

I originally found the error in file-browser, but found it's common to most online apps including the viewer and editor.

Fix exception loading non-legacy fields in most online apps
